import { and, desc, eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { learningDiaries, users } from "../../../db/schema";

function identity(request:Request){return {id:request.headers.get("oai-authenticated-user-id")||"local-user",email:request.headers.get("oai-authenticated-user-email")||"local@learner.app"}}
async function ensureUser(request:Request){const user=identity(request);await (await getDb()).insert(users).values({id:user.id,email:user.email,name:null,timezone:"Asia/Shanghai",createdAt:new Date(),updatedAt:new Date()}).onConflictDoNothing();return user.id}
function publicEntry(row:typeof learningDiaries.$inferSelect){return {...row,createdAt:row.createdAt.toISOString(),updatedAt:row.updatedAt.toISOString()}}

export async function GET(request:Request){try{const uid=identity(request).id;const rows=await (await getDb()).select().from(learningDiaries).where(eq(learningDiaries.userId,uid)).orderBy(desc(learningDiaries.entryDate),desc(learningDiaries.createdAt));return Response.json({entries:rows.map(publicEntry)},{headers:{"cache-control":"private, max-age=30, stale-while-revalidate=300"}})}catch(error){return Response.json({error:error instanceof Error?error.message:"读取日记失败"},{status:500})}}

export async function POST(request:Request){try{const uid=await ensureUser(request);const body=await request.json();const title=String(body.title||"").trim();const content=String(body.content||"").trim();const entryDate=String(body.entryDate||"").trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(entryDate))return Response.json({error:"请选择有效日期"},{status:400});if(!title)return Response.json({error:"请填写日记标题"},{status:400});if(!content)return Response.json({error:"请填写日记内容"},{status:400});if(title.length>80||content.length>10000)return Response.json({error:"日记内容超出长度限制"},{status:400});const now=new Date();const row={id:crypto.randomUUID(),userId:uid,entryDate,title,content,createdAt:now,updatedAt:now};await (await getDb()).insert(learningDiaries).values(row);return Response.json({entry:publicEntry(row)},{status:201})}catch(error){return Response.json({error:error instanceof Error?error.message:"保存日记失败"},{status:500})}}

export async function PATCH(request:Request){try{const uid=await ensureUser(request);const body=await request.json();const id=String(body.id||"");const title=String(body.title||"").trim();const content=String(body.content||"").trim();const entryDate=String(body.entryDate||"").trim();if(!id)return Response.json({error:"缺少日记 ID"},{status:400});if(!/^\d{4}-\d{2}-\d{2}$/.test(entryDate))return Response.json({error:"请选择有效日期"},{status:400});if(!title||!content)return Response.json({error:"标题和日记内容不能为空"},{status:400});if(title.length>80||content.length>10000)return Response.json({error:"日记内容超出长度限制"},{status:400});const db=await getDb();const [stored]=await db.select().from(learningDiaries).where(and(eq(learningDiaries.id,id),eq(learningDiaries.userId,uid))).limit(1);if(!stored)return Response.json({error:"日记不存在"},{status:404});const updatedAt=new Date();await db.update(learningDiaries).set({entryDate,title,content,updatedAt}).where(and(eq(learningDiaries.id,id),eq(learningDiaries.userId,uid)));return Response.json({entry:publicEntry({...stored,entryDate,title,content,updatedAt})})}catch(error){return Response.json({error:error instanceof Error?error.message:"更新日记失败"},{status:500})}}

export async function DELETE(request:Request){try{const uid=await ensureUser(request);const id=new URL(request.url).searchParams.get("id");if(!id)return Response.json({error:"缺少日记 ID"},{status:400});const db=await getDb();const [stored]=await db.select({id:learningDiaries.id}).from(learningDiaries).where(and(eq(learningDiaries.id,id),eq(learningDiaries.userId,uid))).limit(1);if(!stored)return Response.json({error:"日记不存在"},{status:404});await db.delete(learningDiaries).where(and(eq(learningDiaries.id,id),eq(learningDiaries.userId,uid)));return Response.json({ok:true})}catch(error){return Response.json({error:error instanceof Error?error.message:"删除日记失败"},{status:500})}}
