import { and, desc, eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { learningDiaries, users } from "../../../db/schema";

function identity(request:Request){return {id:request.headers.get("oai-authenticated-user-id")||"local-user",email:request.headers.get("oai-authenticated-user-email")||"local@learner.app"}}
async function ensureUser(request:Request){const user=identity(request);await (await getDb()).insert(users).values({id:user.id,email:user.email,name:null,timezone:"Asia/Shanghai",createdAt:new Date(),updatedAt:new Date()}).onConflictDoNothing();return user.id}
function publicEntry(row:typeof learningDiaries.$inferSelect){return {...row,entryType:row.entryType||"feeling",createdAt:row.createdAt.toISOString(),updatedAt:row.updatedAt.toISOString()}}
function taskContent(value:unknown){if(!Array.isArray(value))return "";return value.map(item=>{if(!item||typeof item!=="object")return "";const task=item as {text?:unknown;done?:unknown};const text=String(task.text||"").trim().replace(/\r?\n+/g," ");return text?`- [${task.done?"x":" "}] ${text}`:""}).filter(Boolean).join("\n")}

export async function GET(request:Request){try{const uid=identity(request).id;const rows=await (await getDb()).select().from(learningDiaries).where(eq(learningDiaries.userId,uid)).orderBy(desc(learningDiaries.entryDate),desc(learningDiaries.createdAt));return Response.json({entries:rows.map(publicEntry)},{headers:{"cache-control":"private, max-age=30, stale-while-revalidate=300"}})}catch(error){return Response.json({error:error instanceof Error?error.message:"读取日记失败"},{status:500})}}

export async function POST(request:Request){try{const uid=await ensureUser(request);const body=await request.json();const entryDate=String(body.entryDate||"").trim();const entryType=body.entryType==="task"?"task" as const:"feeling" as const;const title=String(body.title||"").trim()||(entryType==="task"?"当日任务":"");const content=entryType==="task"?(taskContent(body.tasks)||String(body.content||"").trim()):String(body.content||"").trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(entryDate))return Response.json({error:"请选择有效日期"},{status:400});if(!title)return Response.json({error:"请填写日记标题"},{status:400});if(!content)return Response.json({error:entryType==="task"?"请至少添加一项任务":"请填写日记内容"},{status:400});if(title.length>80||content.length>10000)return Response.json({error:"日记内容超出长度限制"},{status:400});const now=new Date();const row={id:crypto.randomUUID(),userId:uid,entryDate,title,content,entryType,createdAt:now,updatedAt:now};await (await getDb()).insert(learningDiaries).values(row);return Response.json({entry:publicEntry(row)},{status:201})}catch{return Response.json({error:"保存日记失败，请稍后重试"},{status:500})}}

export async function PATCH(request:Request){try{const uid=await ensureUser(request);const body=await request.json();const id=String(body.id||"");const entryDate=String(body.entryDate||"").trim();if(!id)return Response.json({error:"缺少日记 ID"},{status:400});if(!/^\d{4}-\d{2}-\d{2}$/.test(entryDate))return Response.json({error:"请选择有效日期"},{status:400});const db=await getDb();const [stored]=await db.select().from(learningDiaries).where(and(eq(learningDiaries.id,id),eq(learningDiaries.userId,uid))).limit(1);if(!stored)return Response.json({error:"日记不存在"},{status:404});const entryType=body.entryType==="task"?"task" as const:body.entryType==="feeling"?"feeling" as const:stored.entryType;const title=String(body.title||"").trim()||(entryType==="task"?"当日任务":"");const content=entryType==="task"?(taskContent(body.tasks)||String(body.content||"").trim()):String(body.content||"").trim();if(!title||!content)return Response.json({error:entryType==="task"?"请至少添加一项任务":"标题和日记内容不能为空"},{status:400});if(title.length>80||content.length>10000)return Response.json({error:"日记内容超出长度限制"},{status:400});const updatedAt=new Date();await db.update(learningDiaries).set({entryDate,title,content,entryType,updatedAt}).where(and(eq(learningDiaries.id,id),eq(learningDiaries.userId,uid)));return Response.json({entry:publicEntry({...stored,entryDate,title,content,entryType,updatedAt})})}catch{return Response.json({error:"更新日记失败，请稍后重试"},{status:500})}}

export async function DELETE(request:Request){try{const uid=await ensureUser(request);const id=new URL(request.url).searchParams.get("id");if(!id)return Response.json({error:"缺少日记 ID"},{status:400});const db=await getDb();const [stored]=await db.select({id:learningDiaries.id}).from(learningDiaries).where(and(eq(learningDiaries.id,id),eq(learningDiaries.userId,uid))).limit(1);if(!stored)return Response.json({error:"日记不存在"},{status:404});await db.delete(learningDiaries).where(and(eq(learningDiaries.id,id),eq(learningDiaries.userId,uid)));return Response.json({ok:true})}catch(error){return Response.json({error:error instanceof Error?error.message:"删除日记失败"},{status:500})}}
