import { eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { learningCards, memoryStates, reviewEvents } from "../../../db/schema";

const zone="Asia/Shanghai";function dayKey(value:Date){return new Intl.DateTimeFormat("en-CA",{timeZone:zone,year:"numeric",month:"2-digit",day:"2-digit"}).format(value)}
export async function GET(request:Request){
  try{
    const uid=request.headers.get("oai-authenticated-user-id")||"local-user";const db=(await getDb());const [cards,states,reviews]=await Promise.all([db.select({id:learningCards.id,createdAt:learningCards.createdAt}).from(learningCards).where(eq(learningCards.userId,uid)),db.select().from(memoryStates).where(eq(memoryStates.userId,uid)),db.select({rating:reviewEvents.rating,reviewedAt:reviewEvents.reviewedAt}).from(reviewEvents).where(eq(reviewEvents.userId,uid))]);const now=new Date();const today=dayKey(now);const cutoff30=now.getTime()-30*86400000;const recent30=reviews.filter(item=>item.reviewedAt.getTime()>=cutoff30);const reviewedDays=new Set(reviews.map(item=>dayKey(item.reviewedAt)));let streak=0;const cursor=new Date(now);if(!reviewedDays.has(today))cursor.setDate(cursor.getDate()-1);while(reviewedDays.has(dayKey(cursor))){streak++;cursor.setDate(cursor.getDate()-1)}const trend=Array.from({length:14},(_,offset)=>{const date=new Date(now);date.setDate(date.getDate()-(13-offset));const key=dayKey(date);return {date:key,label:`${date.getMonth()+1}/${date.getDate()}`,count:reviews.filter(item=>dayKey(item.reviewedAt)===key).length}});const mastered=states.filter(item=>item.status==="mastered").length;const due=cards.filter(card=>{const state=states.find(item=>item.learningCardId===card.id);return !state||(state.status!=="mastered"&&state.nextReviewAt<=now)}).length;return Response.json({totalCards:cards.length,dueCount:due,newToday:cards.filter(card=>dayKey(card.createdAt)===today).length,completedToday:reviews.filter(item=>dayKey(item.reviewedAt)===today).length,streak,recent30:recent30.length,retention:recent30.length?Math.round(recent30.filter(item=>item.rating!=="again").length/recent30.length*100):0,mastered,masteredRate:cards.length?Math.round(mastered/cards.length*100):0,trend});
  }catch(error){return Response.json({error:error instanceof Error?error.message:"读取学习统计失败"},{status:500})}
}
