import { and, asc, eq, inArray } from "drizzle-orm";
import { getDb } from "../../../db";
import { learningCardTags, tags, users } from "../../../db/schema";

function identity(request:Request){return {id:request.headers.get("oai-authenticated-user-id")||"local-user",email:request.headers.get("oai-authenticated-user-email")||"local@learner.app"}}
function normalize(value:string){return value.trim().replace(/\s+/g," ").toLocaleLowerCase()}
async function ensureUser(request:Request){const user=identity(request);await (await getDb()).insert(users).values({id:user.id,email:user.email,name:null,timezone:"Asia/Shanghai",createdAt:new Date(),updatedAt:new Date()}).onConflictDoNothing();return user.id}

export async function GET(request:Request){try{const uid=await ensureUser(request);const db=await getDb();const rows=await db.select().from(tags).where(eq(tags.userId,uid)).orderBy(asc(tags.sortOrder),asc(tags.name));const links=rows.length?await db.select({tagId:learningCardTags.tagId}).from(learningCardTags).where(inArray(learningCardTags.tagId,rows.map(tag=>tag.id))):[];const counts=new Map<string,number>();for(const link of links)counts.set(link.tagId,(counts.get(link.tagId)||0)+1);return Response.json({tags:rows.map(tag=>({...tag,count:counts.get(tag.id)||0}))})}catch(error){return Response.json({error:error instanceof Error?error.message:"读取标签失败"},{status:500})}}

export async function POST(request:Request){try{const uid=await ensureUser(request);const body=await request.json();const name=String(body.name||"").trim().replace(/\s+/g," ");const normalizedName=normalize(name);const type=body.type==="knowledge"?"knowledge" as const:"attribute" as const;const parentId=type==="knowledge"&&body.parentId?String(body.parentId):null;if(!name)return Response.json({error:"标签名不能为空"},{status:400});if(name.length>40)return Response.json({error:"标签名不能超过 40 个字符"},{status:400});const db=await getDb();if(parentId){const [parent]=await db.select({id:tags.id}).from(tags).where(and(eq(tags.id,parentId),eq(tags.userId,uid),eq(tags.type,"knowledge"))).limit(1);if(!parent)return Response.json({error:"父级知识节点不存在"},{status:400})}const [existing]=await db.select().from(tags).where(and(eq(tags.userId,uid),eq(tags.normalizedName,normalizedName))).limit(1);if(existing){if(type==="knowledge"&&existing.type!=="knowledge"){await db.update(tags).set({type,parentId,updatedAt:new Date()}).where(eq(tags.id,existing.id));return Response.json({tag:{...existing,type,parentId},created:false})}return Response.json({tag:existing,created:false})}const now=new Date();const tag={id:crypto.randomUUID(),userId:uid,name,normalizedName,type,parentId,description:String(body.description||"").trim()||null,sortOrder:Number.isFinite(body.sortOrder)?Number(body.sortOrder):0,createdAt:now,updatedAt:now};await db.insert(tags).values(tag);return Response.json({tag,created:true},{status:201})}catch(error){return Response.json({error:error instanceof Error?error.message:"创建标签失败"},{status:500})}}

export async function PATCH(request:Request){try{const uid=await ensureUser(request);const body=await request.json();const id=String(body.id||"");const name=String(body.name||"").trim().replace(/\s+/g," ");if(!id||!name)return Response.json({error:"节点名称不能为空"},{status:400});const db=await getDb();const rows=await db.select().from(tags).where(eq(tags.userId,uid));const stored=rows.find(tag=>tag.id===id);if(!stored)return Response.json({error:"知识节点不存在"},{status:404});const parentId=body.parentId?String(body.parentId):null;if(parentId===id)return Response.json({error:"节点不能成为自己的父级"},{status:400});let cursor=parentId;while(cursor){if(cursor===id)return Response.json({error:"不能将节点移动到自己的子节点下"},{status:400});cursor=rows.find(tag=>tag.id===cursor)?.parentId||null}await db.update(tags).set({name,normalizedName:normalize(name),type:"knowledge",parentId,description:String(body.description||"").trim()||null,sortOrder:Number.isFinite(body.sortOrder)?Number(body.sortOrder):stored.sortOrder,updatedAt:new Date()}).where(and(eq(tags.id,id),eq(tags.userId,uid)));return Response.json({tag:{...stored,name,normalizedName:normalize(name),type:"knowledge",parentId,description:String(body.description||"").trim()||null}})}catch(error){return Response.json({error:error instanceof Error?error.message:"更新知识节点失败"},{status:500})}}

export async function DELETE(request:Request){try{const uid=await ensureUser(request);const id=new URL(request.url).searchParams.get("id");if(!id)return Response.json({error:"缺少节点 id"},{status:400});const db=await getDb();const [stored]=await db.select({id:tags.id}).from(tags).where(and(eq(tags.id,id),eq(tags.userId,uid))).limit(1);if(!stored)return Response.json({error:"知识节点不存在"},{status:404});await db.update(tags).set({parentId:null,updatedAt:new Date()}).where(and(eq(tags.userId,uid),eq(tags.parentId,id)));await db.delete(learningCardTags).where(eq(learningCardTags.tagId,id));await db.delete(tags).where(and(eq(tags.id,id),eq(tags.userId,uid)));return Response.json({ok:true})}catch(error){return Response.json({error:error instanceof Error?error.message:"删除知识节点失败"},{status:500})}}
