import { and, asc, eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { tags, users } from "../../../db/schema";

function identity(request:Request){return {id:request.headers.get("oai-authenticated-user-id")||"local-user",email:request.headers.get("oai-authenticated-user-email")||"local@learner.app"}}
function normalize(value:string){return value.trim().replace(/\s+/g," ").toLocaleLowerCase()}
async function ensureUser(request:Request){const user=identity(request);await (await getDb()).insert(users).values({id:user.id,email:user.email,name:null,timezone:"Asia/Shanghai",createdAt:new Date(),updatedAt:new Date()}).onConflictDoNothing();return user.id}

export async function GET(request:Request){try{const uid=await ensureUser(request);const rows=await (await getDb()).select({id:tags.id,name:tags.name}).from(tags).where(eq(tags.userId,uid)).orderBy(asc(tags.name));return Response.json({tags:rows})}catch(error){return Response.json({error:error instanceof Error?error.message:"读取标签失败"},{status:500})}}
export async function POST(request:Request){try{const uid=await ensureUser(request);const body=await request.json();const name=String(body.name||"").trim().replace(/\s+/g," ");const normalizedName=normalize(name);if(!name)return Response.json({error:"标签名不能为空"},{status:400});if(name.length>40)return Response.json({error:"标签名不能超过 40 个字符"},{status:400});const db=(await getDb());const [existing]=await db.select({id:tags.id,name:tags.name}).from(tags).where(and(eq(tags.userId,uid),eq(tags.normalizedName,normalizedName))).limit(1);if(existing)return Response.json({tag:existing,created:false});const now=new Date();const tag={id:crypto.randomUUID(),userId:uid,name,normalizedName,createdAt:now,updatedAt:now};await db.insert(tags).values(tag).onConflictDoNothing();const [saved]=await db.select({id:tags.id,name:tags.name}).from(tags).where(and(eq(tags.userId,uid),eq(tags.normalizedName,normalizedName))).limit(1);return Response.json({tag:saved,created:saved?.id===tag.id},{status:201})}catch(error){return Response.json({error:error instanceof Error?error.message:"创建标签失败"},{status:500})}}
