import { and, eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { modelConfigs } from "../../../db/schema";
import { encryptApiKey } from "../../../lib/model-secrets";

function userId(request:Request){return request.headers.get("oai-authenticated-user-id")||"local-user"}
function publicConfig(row:typeof modelConfigs.$inferSelect){const {encryptedApiKey,...safe}=row;return {...safe,apiKey:"",keyLast4:row.keyLast4}}
export async function GET(request:Request){try{const rows=await getDb().select().from(modelConfigs).where(eq(modelConfigs.userId,userId(request)));return Response.json({configs:rows.map(publicConfig)})}catch(e){return Response.json({error:e instanceof Error?e.message:"读取模型失败"},{status:500})}}
export async function POST(request:Request){try{const body=await request.json();if(!body.apiKey?.trim()||!body.model?.trim())return Response.json({error:"模型和 API Key 为必填项"},{status:400});const db=getDb();const uid=userId(request);const existing=await db.select({id:modelConfigs.id}).from(modelConfigs).where(eq(modelConfigs.userId,uid));const now=new Date();const row={id:crypto.randomUUID(),userId:uid,provider:String(body.provider),providerLabel:String(body.providerLabel),model:String(body.model),baseUrl:String(body.baseUrl||""),encryptedApiKey:await encryptApiKey(body.apiKey.trim()),keyLast4:body.apiKey.trim().slice(-4),enabled:true,isDefault:existing.length===0,createdAt:now,updatedAt:now};await db.insert(modelConfigs).values(row);return Response.json({config:publicConfig(row)},{status:201})}catch(e){return Response.json({error:e instanceof Error?e.message:"保存模型失败"},{status:500})}}
export async function PATCH(request:Request){try{const body=await request.json();const uid=userId(request);const db=getDb();if(body.isDefault)await db.update(modelConfigs).set({isDefault:false,updatedAt:new Date()}).where(eq(modelConfigs.userId,uid));const changes:Record<string,unknown>={updatedAt:new Date()};if(typeof body.enabled==="boolean")changes.enabled=body.enabled;if(typeof body.isDefault==="boolean")changes.isDefault=body.isDefault;await db.update(modelConfigs).set(changes).where(and(eq(modelConfigs.id,body.id),eq(modelConfigs.userId,uid)));return Response.json({ok:true})}catch(e){return Response.json({error:e instanceof Error?e.message:"更新失败"},{status:500})}}
export async function DELETE(request:Request){try{const id=new URL(request.url).searchParams.get("id");if(!id)return Response.json({error:"缺少 id"},{status:400});await getDb().delete(modelConfigs).where(and(eq(modelConfigs.id,id),eq(modelConfigs.userId,userId(request))));return Response.json({ok:true})}catch(e){return Response.json({error:e instanceof Error?e.message:"删除失败"},{status:500})}}
