"use client";

import { useEffect, useMemo, useState } from "react";

type View = "home" | "upload" | "cards" | "study" | "stats" | "settings";
type Rating = "again" | "hard" | "good" | "easy";
type ModelConfig = { id:string; provider:string; providerLabel:string; model:string; apiKey?:string; keyLast4?:string; baseUrl:string; enabled:boolean; isDefault:boolean };
type Card = { id:number; type:string; front:string; back:string; path:string; tags:string[]; interval:string; tone:string };
type AnalyzedQuestion = { order:number; questionNumber:string; stem:string; options:string[]; answer:string; solution:string; knowledgePoints:{name:string;summary:string}[]; thinkingModel:{name:string;description:string;steps:string[]}; difficulty:number; confirmed?:boolean };

const cards:Card[] = [
  { id: 1, type: "思维模型", front: "看到“已知 GCD 和 LCM 求两个整数”，第一步想到什么？", back: "设 a = gcd × x，b = gcd × y，且 gcd(x,y)=1，再结合 a×b = gcd×lcm。", path: "199 管综 / 数学 / 算术", tags: ["错题", "必背"], interval: "今天", tone: "violet" },
  { id: 2, type: "知识点", front: "充分条件和必要条件的逻辑关系是什么？", back: "若 P → Q，则 P 是 Q 的充分条件，Q 是 P 的必要条件。", path: "199 管综 / 逻辑 / 形式逻辑", tags: ["高频"], interval: "今天", tone: "blue" },
  { id: 3, type: "原题", front: "已知 a、b 的最大公约数为 6，最小公倍数为 90……", back: "由 a×b = gcd(a,b)×lcm(a,b) 建立乘积关系，再引入互质变量求解。", path: "199 管综 / 数学 / 算术", tags: ["二刷"], interval: "明天", tone: "orange" },
  { id: 4, type: "背诵", front: "What does 'in light of' mean?", back: "鉴于；考虑到。例：In light of recent events, we changed the plan.", path: "英语二 / 阅读 / 熟词僻义", tags: ["没掌握"], interval: "3 天后", tone: "green" },
];

const nav = [
  ["home", "首页", "◈"], ["upload", "上传学习内容", "↑"], ["cards", "学习卡片", "▱"], ["stats", "学习统计", "⌑"], ["settings", "设置", "⚙"],
] as const;

export default function Home() {
  const [view, setView] = useState<View>("home");
  const [studyIndex, setStudyIndex] = useState(0);
  const [revealed, setRevealed] = useState(false);
  const [completed, setCompleted] = useState(18);
  const [query, setQuery] = useState("");
  const [uploadMode, setUploadMode] = useState<"memorization" | "question" | null>(null);
  const [notice, setNotice] = useState("");
  const [modelConfigs,setModelConfigs]=useState<ModelConfig[]>([]);
  const [generatedCards,setGeneratedCards]=useState<Card[]>([]);
  const allCards=useMemo(()=>[...generatedCards,...cards],[generatedCards]);
  const dueCards = allCards.slice(0, 2);
  const activeCard = dueCards[studyIndex % dueCards.length];
  const filtered = useMemo(() => allCards.filter(c => `${c.front}${c.tags.join("")}${c.path}`.toLowerCase().includes(query.toLowerCase())), [query,allCards]);
  const activeModel=modelConfigs.find(c=>c.enabled&&c.isDefault)||modelConfigs.find(c=>c.enabled);

  useEffect(()=>{let cancelled=false;fetch("/api/models").then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||"读取模型配置失败");if(!cancelled)setModelConfigs(data.configs||[])}).catch(error=>{if(!cancelled)setNotice(error instanceof Error?error.message:"读取模型配置失败")});return()=>{cancelled=true}},[]);

  function rate(rating: Rating) {
    const label = { again: "重新学习", hard: "稍后巩固", good: "4 天后复习", easy: "15 天后复习" }[rating];
    setNotice(`已记录·${label}`);
    setCompleted(v => v + 1);
    setTimeout(() => { setStudyIndex(v => v + 1); setRevealed(false); setNotice(""); }, 650);
  }

  return (
    <main className="app-shell">
      <aside className="sidebar">
        <button className="brand" onClick={() => setView("home")}><span className="brand-mark">L</span><span>Learner<small>个人学习机</small></span></button>
        <nav>{nav.map(([id, label, icon]) => <button key={id} className={view === id ? "active" : ""} onClick={() => setView(id as View)}><i>{icon}</i>{label}{id === "cards" && <b>1,238</b>}</button>)}</nav>
        <div className="sidebar-card"><span>本周连续学习</span><strong>6 <small>天</small></strong><div className="week">{["M","T","W","T","F","S","S"].map((d,i)=><i className={i<6?"done":""} key={i}>{i<6?"✓":d}</i>)}</div></div>
        <button className="profile"><span>林</span><span>林晓宇<small>学习设置</small></span><i>···</i></button>
      </aside>

      <section className="workspace">
        <header className="topbar"><div className="mobile-logo">Learner</div><button className="search" onClick={() => setView("cards")}><span>⌕</span>搜索卡片、标签或目录 <kbd>⌘ K</kbd></button><div className="top-actions"><button>○</button><button>♧</button><span className="avatar">林</span></div></header>

        {view === "home" && <Dashboard onStudy={() => setView("study")} onUpload={() => setView("upload")} onCards={() => setView("cards")} completed={completed} />}
        {view === "cards" && <CardLibrary cards={filtered} query={query} setQuery={setQuery} onStudy={() => setView("study")} />}
        {view === "upload" && <AIUpload mode={uploadMode} setMode={setUploadMode} model={activeModel} onCardsGenerated={newCards=>{setGeneratedCards(prev=>[...newCards,...prev]);setView("cards")}} />}
        {view === "study" && <Study card={activeCard} revealed={revealed} setRevealed={setRevealed} rate={rate} current={studyIndex+1} notice={notice} onExit={() => setView("home")} />}
        {view === "stats" && <Stats />}
        {view === "settings" && <Settings configs={modelConfigs} setConfigs={setModelConfigs} />}
      </section>
    </main>
  );
}

function Dashboard({onStudy,onUpload,onCards,completed}:{onStudy:()=>void;onUpload:()=>void;onCards:()=>void;completed:number}) {
  return <div className="page dashboard"><div className="eyebrow">周三 · 8月19日</div><h1>早上好，林晓宇 <span>✦</span></h1><p className="lead">今天也来让知识留下来。</p>
    <section className="hero-card"><div className="hero-copy"><div className="hero-label"><i></i>今日学习</div><div className="hero-num">36 <small>张待复习</small></div><p>其中 8 张是易错题，优先复习会更高效</p><button className="primary light" onClick={onStudy}>开始学习 <span>→</span></button></div><div className="orbit"><span className="orb one">逻辑</span><span className="orb two">GCD</span><span className="orb three">if</span><span className="orb four">π</span><div className="rings"></div></div></section>
    <div className="metrics"><article><span className="metric-icon orange">◷</span><div><small>待复习</small><strong>36</strong></div><em>↑ 8 张易错</em></article><article><span className="metric-icon blue">+</span><div><small>今日新卡</small><strong>20</strong></div><em>建议上限 25</em></article><article><span className="metric-icon green">✓</span><div><small>今日已完成</small><strong>{completed}</strong></div><em>{Math.min(100, Math.round(completed/54*100))}% 进度</em></article></div>
    <div className="section-title"><div><h2>继续学习</h2><p>从最近的记忆状态继续</p></div><button onClick={onCards}>查看全部 →</button></div>
    <div className="recent-grid"><article className="recent orange-border"><div><span>数学 · 算术</span><b>12 / 48</b></div><h3>最大公约数与最小公倍数</h3><p>上次学习：昨天</p><progress value="25" max="100" /></article><article className="recent violet-border"><div><span>逻辑 · 形式逻辑</span><b>31 / 65</b></div><h3>充分条件、必要条件与假言命题</h3><p>上次学习：3 天前</p><progress value="48" max="100" /></article></div>
    <section className="create-panel"><div className="spark">✦</div><div><h2>把新知识变成长期记忆</h2><p>上传截图或照片，AI 会拆分知识、解题并生成学习卡片。</p></div><button className="primary" onClick={onUpload}>↑ 上传学习内容</button></section>
  </div>;
}

function CardLibrary({cards:items,query,setQuery,onStudy}:{cards:Card[];query:string;setQuery:(v:string)=>void;onStudy:()=>void}) {
  const list = items;
  return <div className="page"><div className="page-heading"><div><span className="eyebrow">知识库</span><h1>学习卡片</h1><p>1,238 张卡片，每一张都有完整的知识来源。</p></div><button className="primary" onClick={onStudy}>▶ 学习到期卡片</button></div><div className="library-tools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索卡片、标签或目录…"/><button>全部类型 ⌄</button><button>今日待复习</button></div><div className="card-list">{list.map(card=><article className="knowledge-card" key={card.id}><div className={`type-mark ${card.tone}`}>{card.type.slice(0,1)}</div><div className="card-body"><div><span className={`type-pill ${card.tone}`}>{card.type}</span><span className="path">{card.path}</span></div><h3>{card.front}</h3><div className="tags">{card.tags.map(t=><span key={t}>#{t}</span>)}</div></div><div className="due"><small>下次复习</small><strong>{card.interval}</strong><button aria-label="更多">···</button></div></article>)}</div></div>;
}

function Upload({mode,setMode}:{mode:"memorization"|"question"|null;setMode:(m:"memorization"|"question")=>void}) {
  const [file,setFile]=useState<File|null>(null); const [preview,setPreview]=useState(""); const [dragging,setDragging]=useState(false); const [message,setMessage]=useState("");
  function acceptImage(next?:File){if(!next)return;if(!next.type.startsWith("image/")){setMessage("请选择图片文件");return}setFile(next);setMessage("")}
  useEffect(()=>{if(!file){setPreview("");return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);
  useEffect(()=>{function onPaste(event:ClipboardEvent){const image=Array.from(event.clipboardData?.items||[]).find(item=>item.type.startsWith("image/"))?.getAsFile();if(image){event.preventDefault();acceptImage(new File([image],`clipboard-${Date.now()}.${image.type.split("/")[1]||"png"}`,{type:image.type}));setMessage("已从剪贴板粘贴图片")}}window.addEventListener("paste",onPaste);return()=>window.removeEventListener("paste",onPaste)},[]);
  return <div className="page upload-page"><div className="page-heading"><div><span className="eyebrow">AI 学习助手</span><h1>上传学习内容</h1><p>拖拽、点击选择，或直接粘贴截图，让 AI 把它变成可以长期复习的卡片。</p></div></div><div className="upload-layout"><section><div className={`dropzone ${file?"has-file":""} ${dragging?"dragging":""}`} onDragEnter={e=>{e.preventDefault();setDragging(true)}} onDragOver={e=>e.preventDefault()} onDragLeave={e=>{e.preventDefault();setDragging(false)}} onDrop={e=>{e.preventDefault();setDragging(false);acceptImage(e.dataTransfer.files[0])}}><input aria-label="选择图片" type="file" accept="image/*" onChange={e=>acceptImage(e.target.files?.[0])}/>{preview?<><img className="upload-preview" src={preview} alt="待上传图片预览"/><button className="remove-upload" onClick={e=>{e.preventDefault();e.stopPropagation();setFile(null);setMessage("")}} aria-label="移除图片">×</button><div className="file-summary"><strong>{file?.name}</strong><span>{file?`${(file.size/1024/1024).toFixed(2)} MB · ${file.type.replace("image/","").toUpperCase()}`:""}</span></div></>:<><div className="upload-icon">↑</div><h2>{dragging?"松手即可添加图片":"拖拽图片到这里"}</h2><p>点击选择，或按 <kbd>⌘ V</kbd> / <kbd>Ctrl V</kbd> 粘贴截图</p><div className="format-hint">PNG、JPG、WEBP</div></>}</div>{message&&<div className={`upload-message ${file?"success":"error"}`}>{file?"✓":"!"} {message}</div>}<h3 className="mode-title">你希望如何处理这份资料？</h3><div className="mode-grid"><button className={mode==="memorization"?"selected":""} onClick={()=>setMode("memorization")}><i>◇</i><strong>背诵内容</strong><span>提取独立知识点，自动生成问题与答案</span></button><button className={mode==="question"?"selected":""} onClick={()=>setMode("question")}><i>∑</i><strong>题目模式</strong><span>识别并拆题，生成答案、解析与思维模型</span></button></div><button className="primary wide" disabled={!file||!mode}>{file&&mode?"开始 AI 解析 →":"请先上传图片并选择模式"}</button></section><aside className="pipeline"><h3>解析流程</h3>{["图片识别与内容拆分","逐项 AI 理解与生成","你审核、修改 AI 结果","选择并生成学习卡片"].map((x,i)=><div key={x}><b>{i+1}</b><span>{x}<small>{i===2?"结果不会自动入库":""}</small></span></div>)}<p>✦ 原始资料会永久保留，每张卡片都可回溯来源。</p></aside></div></div>
}

function AIUpload({mode,setMode,model,onCardsGenerated}:{mode:"memorization"|"question"|null;setMode:(m:"memorization"|"question")=>void;model?:ModelConfig;onCardsGenerated:(cards:Card[])=>void}){
  const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState("");const [dragging,setDragging]=useState(false);const [phase,setPhase]=useState<"upload"|"analyzing"|"review">("upload");const [progress,setProgress]=useState(0);const [questions,setQuestions]=useState<AnalyzedQuestion[]>([]);const [error,setError]=useState("");
  function acceptImage(next?:File){if(!next)return;if(!next.type.startsWith("image/")){setError("请上传图片文件");return}setFile(next);setError("");setQuestions([]);setPhase("upload")}
  useEffect(()=>{if(!file){setPreview("");return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);
  useEffect(()=>{function paste(e:ClipboardEvent){const image=Array.from(e.clipboardData?.items||[]).find(i=>i.type.startsWith("image/"))?.getAsFile();if(image){e.preventDefault();acceptImage(image)}}window.addEventListener("paste",paste);return()=>window.removeEventListener("paste",paste)},[]);
  async function analyze(){if(!file||!mode)return;setPhase("analyzing");setError("");setProgress(12);const timer=setInterval(()=>setProgress(v=>Math.min(v+Math.ceil(Math.random()*8),88)),700);try{const dataUrl=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file)});const response=await fetch("/api/ai/analyze",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({image:dataUrl,mode,modelConfigId:model?.id,provider:model?.provider||"openai",model:model?.model||"gpt-5.4",baseUrl:model?.baseUrl})});const data=await response.json();if(!response.ok)throw new Error(data.error||"AI 解析失败");setQuestions((data.questions||[]).map((q:AnalyzedQuestion)=>({...q,confirmed:false})));setProgress(100);setTimeout(()=>setPhase("review"),350)}catch(e){setError(e instanceof Error?e.message:"解析失败");setPhase("upload")}finally{clearInterval(timer)}}
  function updateQuestion(index:number,patch:Partial<AnalyzedQuestion>){setQuestions(items=>items.map((q,i)=>i===index?{...q,...patch}:q))}
  function generateCards(){const created=questions.filter(q=>q.confirmed).map((q,i):Card=>({id:Date.now()+i,type:"原题",front:q.stem+(q.options.length?`\n${q.options.join("\n")}`:""),back:`答案：${q.answer}\n\n解析：${q.solution}`,path:"AI 解析 / 待归类",tags:q.knowledgePoints.slice(0,3).map(k=>k.name),interval:"新卡片",tone:"orange"}));onCardsGenerated(created)}
  if(phase==="analyzing")return <div className="page analysis-page"><div className="analysis-loader"><div className="scan-art"><img src={preview} alt="正在解析"/><i style={{top:`${Math.min(progress,92)}%`}}></i></div><span className="eyebrow">AI PIPELINE</span><h1>正在识别并拆分题目…</h1><p>{progress<35?"识别题目边界与公式":progress<65?"逐题生成答案与解析":"提炼知识点和可迁移思维模型"}</p><div className="analysis-progress"><i style={{width:`${progress}%`}}></i></div><b>{progress}%</b><small>请不要关闭页面，复杂题目可能需要几十秒</small></div></div>;
  if(phase==="review")return <div className="page review-page"><div className="review-heading"><div><span className="eyebrow">AI 解析完成</span><h1>识别到 {questions.length} 道题</h1><p>请逐题审核。AI 的结果只是建议，确认后才会生成卡片。</p></div><button className="secondary" onClick={()=>setPhase("upload")}>重新上传</button></div><div className="review-list">{questions.map((q,index)=><article className={q.confirmed?"confirmed":""} key={index}><header><div><b>题目 {q.questionNumber||index+1}</b><span>难度 {q.difficulty}/5</span></div><label><input type="checkbox" checked={!!q.confirmed} onChange={e=>updateQuestion(index,{confirmed:e.target.checked})}/>{q.confirmed?"已确认":"确认无误"}</label></header><label>原始题目<textarea value={q.stem} onChange={e=>updateQuestion(index,{stem:e.target.value})}/></label>{q.options.length>0&&<div className="review-options">{q.options.map((o,i)=><span key={i}>{o}</span>)}</div>}<div className="review-columns"><label>AI 答案<textarea value={q.answer} onChange={e=>updateQuestion(index,{answer:e.target.value})}/></label><label>AI 解析<textarea value={q.solution} onChange={e=>updateQuestion(index,{solution:e.target.value})}/></label></div><div className="knowledge-row"><div><small>知识点</small>{q.knowledgePoints.map(k=><span key={k.name}>#{k.name}</span>)}</div><div className="thinking-box"><small>思维模型</small><strong>{q.thinkingModel.name}</strong><p>{q.thinkingModel.description}</p><ol>{q.thinkingModel.steps.map(s=><li key={s}>{s}</li>)}</ol></div></div></article>)}</div><div className="review-footer"><span>已确认 {questions.filter(q=>q.confirmed).length} / {questions.length} 道题</span><button className="primary" disabled={!questions.some(q=>q.confirmed)} onClick={generateCards}>为已确认题目生成 {questions.filter(q=>q.confirmed).length} 张卡片 →</button></div></div>;
  return <div className="page upload-page"><div className="page-heading"><div><span className="eyebrow">AI 学习助手</span><h1>上传学习内容</h1><p>拖拽、点击选择，或直接粘贴截图。</p></div>{model&&<div className="active-model">✦ {model.providerLabel} · {model.model}</div>}</div><div className="upload-layout"><section><div className={`dropzone ${file?"has-file":""} ${dragging?"dragging":""}`} onDragEnter={e=>{e.preventDefault();setDragging(true)}} onDragOver={e=>e.preventDefault()} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);acceptImage(e.dataTransfer.files[0])}}><input aria-label="选择图片" type="file" accept="image/*" onChange={e=>acceptImage(e.target.files?.[0])}/>{preview?<><img className="upload-preview" src={preview} alt="待解析图片"/><button className="remove-upload" onClick={e=>{e.preventDefault();e.stopPropagation();setFile(null)}}>×</button><div className="file-summary"><strong>{file?.name}</strong><span>{file?`${(file.size/1024/1024).toFixed(2)} MB`:""}</span></div></>:<><div className="upload-icon">↑</div><h2>{dragging?"松手即可添加图片":"拖拽图片到这里"}</h2><p>点击选择，或按 <kbd>⌘ V</kbd> / <kbd>Ctrl V</kbd> 粘贴</p></>}</div>{error&&<div className="upload-message error">! {error}</div>}<h3 className="mode-title">你希望如何处理这份资料？</h3><div className="mode-grid"><button className={mode==="memorization"?"selected":""} onClick={()=>setMode("memorization")}><i>◇</i><strong>背诵内容</strong><span>提取知识点并生成问答</span></button><button className={mode==="question"?"selected":""} onClick={()=>setMode("question")}><i>∑</i><strong>题目模式</strong><span>拆题、解答、解析与思维模型</span></button></div><button className="primary wide" disabled={!file||!mode} onClick={analyze}>{file&&mode?"开始 AI 解析 →":"请先上传图片并选择模式"}</button></section><aside className="pipeline"><h3>真实解析流程</h3>{["识别题目数量并拆分","逐题生成答案与解析","总结知识点与思维模型","人工确认后生成多张卡片"].map((x,i)=><div key={x}><b>{i+1}</b><span>{x}</span></div>)}</aside></div></div>
}

function Study({card,revealed,setRevealed,rate,current,notice,onExit}:{card:(typeof cards)[0];revealed:boolean;setRevealed:(v:boolean)=>void;rate:(r:Rating)=>void;current:number;notice:string;onExit:()=>void}) { return <div className="study-page"><header><button onClick={onExit}>×</button><div><span>今日学习</span><progress value={current} max="36"/><b>{current} / 36</b></div><button>···</button></header><div className="study-stage"><div className={`flashcard ${revealed?"revealed":""}`}><div className="flash-meta"><span>{card.type}</span><small>{card.path}</small></div><div className="flash-front"><small>问题</small><h2>{card.front}</h2></div>{revealed&&<div className="flash-back"><small>答案与解题模型</small><p>{card.back}</p></div>}<div className="flash-tags">{card.tags.map(t=><span key={t}>#{t}</span>)}</div></div>{!revealed?<button className="reveal" onClick={()=>setRevealed(true)}>查看答案 <kbd>Space</kbd></button>:<div className="ratings"><p>这次回忆得怎么样？</p><div><button onClick={()=>rate("again")}><b>Again</b><span>完全忘记</span><kbd>1</kbd></button><button onClick={()=>rate("hard")}><b>Hard</b><span>比较困难</span><kbd>2</kbd></button><button onClick={()=>rate("good")}><b>Good</b><span>正常想起</span><kbd>3</kbd></button><button onClick={()=>rate("easy")}><b>Easy</b><span>非常熟练</span><kbd>4</kbd></button></div></div>}{notice&&<div className="toast">{notice}</div>}</div></div> }

function Stats(){ return <div className="page"><div className="page-heading"><div><span className="eyebrow">记忆趋势</span><h1>学习统计</h1><p>看见每一次回忆如何让知识更牢固。</p></div></div><div className="stat-grid"><article><small>近 30 天复习</small><strong>684</strong><em>↑ 18%</em></article><article><small>平均记忆率</small><strong>87%</strong><em>稳定</em></article><article><small>已掌握</small><strong>426</strong><em>34% 卡片</em></article></div><section className="chart"><h3>近 14 天学习量</h3><div className="bars">{[34,52,41,65,48,72,28,56,82,61,76,90,68,84].map((n,i)=><i key={i} style={{height:`${n}%`}}><span>{n}</span></i>)}</div><div className="chart-labels"><span>8/06</span><span>8/12</span><span>今天</span></div></section></div> }

const providers = {
  openai:{label:"OpenAI",baseUrl:"https://api.openai.com/v1",models:["gpt-5.4","gpt-5.4-mini","gpt-4.1"]},
  anthropic:{label:"Anthropic",baseUrl:"https://api.anthropic.com/v1",models:["claude-sonnet-4-5","claude-opus-4-1"]},
  gemini:{label:"Google Gemini",baseUrl:"https://generativelanguage.googleapis.com/v1beta",models:["gemini-2.5-pro","gemini-2.5-flash"]},
  deepseek:{label:"DeepSeek",baseUrl:"https://api.deepseek.com/v1",models:["deepseek-chat","deepseek-reasoner"]},
  custom:{label:"自定义兼容接口",baseUrl:"",models:[] as string[]},
};

function Settings({configs,setConfigs}:{configs:ModelConfig[];setConfigs:(next:ModelConfig[])=>void}){
  const [adding,setAdding]=useState(false);const [provider,setProvider]=useState<keyof typeof providers>("openai");const [model,setModel]=useState(providers.openai.models[0]);const [customModel,setCustomModel]=useState("");const [key,setKey]=useState("");const [baseUrl,setBaseUrl]=useState(providers.openai.baseUrl);const [showKey,setShowKey]=useState(false);const [saving,setSaving]=useState(false);const [settingsError,setSettingsError]=useState("");
  function chooseProvider(value:keyof typeof providers){setProvider(value);setModel(providers[value].models[0]||"");setBaseUrl(providers[value].baseUrl);setCustomModel("")}
  async function add(){const finalModel=provider==="custom"?customModel:model;if(!key.trim()||!finalModel.trim())return;setSaving(true);setSettingsError("");try{const response=await fetch("/api/models",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({provider,providerLabel:providers[provider].label,model:finalModel,apiKey:key.trim(),baseUrl:baseUrl.trim()})});const data=await response.json();if(!response.ok)throw new Error(data.error||"保存失败");setConfigs([...configs,data.config]);setKey("");setAdding(false)}catch(error){setSettingsError(error instanceof Error?error.message:"保存失败")}finally{setSaving(false)}}
  async function update(id:string,change:Partial<ModelConfig>){setSettingsError("");try{const response=await fetch("/api/models",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,...change})});const data=await response.json();if(!response.ok)throw new Error(data.error||"更新失败");setConfigs(configs.map(c=>c.id===id?{...c,...change}:change.isDefault?{...c,isDefault:false}:c))}catch(error){setSettingsError(error instanceof Error?error.message:"更新失败")}}
  async function remove(id:string){setSettingsError("");try{const response=await fetch(`/api/models?id=${encodeURIComponent(id)}`,{method:"DELETE"});const data=await response.json();if(!response.ok)throw new Error(data.error||"删除失败");setConfigs(configs.filter(c=>c.id!==id))}catch(error){setSettingsError(error instanceof Error?error.message:"删除失败")}}
  return <div className="page settings-page"><div className="page-heading"><div><span className="eyebrow">系统设置</span><h1>模型管理</h1><p>管理 AI 解析使用的厂商、模型和 API Key。</p></div><button className="primary" onClick={()=>setAdding(true)}>+ 添加模型</button></div><div className="security-note"><span>✦</span><div><strong>密钥安全</strong><p>API Key 经服务端加密后保存在生产数据库，列表中只显示末四位；刷新页面或发布新版本都不会丢失。</p></div></div>{settingsError&&<div className="upload-message error">! {settingsError}</div>}{configs.length===0?<div className="empty-models"><div>⌘</div><h2>还没有可用的 AI 模型</h2><p>添加一个厂商和 API Key，才能开始图片识题与解析。</p><button onClick={()=>setAdding(true)}>+ 添加第一个模型</button></div>:<div className="model-list">{configs.map(config=><article key={config.id}><div className={`provider-logo ${config.provider}`}>{config.providerLabel.slice(0,2)}</div><div className="model-main"><div><h3>{config.providerLabel}</h3>{config.isDefault&&<span>默认解析模型</span>}</div><strong>{config.model}</strong><small>{config.baseUrl} · Key ••••{config.keyLast4||config.apiKey?.slice(-4)||""}</small></div><label className="switch"><input type="checkbox" checked={config.enabled} onChange={e=>void update(config.id,{enabled:e.target.checked})}/><i></i></label><button className="model-action" disabled={config.isDefault} onClick={()=>void update(config.id,{isDefault:true})}>{config.isDefault?"已默认":"设为默认"}</button><button className="delete-model" onClick={()=>void remove(config.id)}>删除</button></article>)}</div>}{adding&&<div className="modal-backdrop" onMouseDown={()=>setAdding(false)}><section className="model-modal" onMouseDown={e=>e.stopPropagation()}><header><div><span className="eyebrow">新建连接</span><h2>添加 AI 模型</h2></div><button onClick={()=>setAdding(false)}>×</button></header><label>模型厂商<select value={provider} onChange={e=>chooseProvider(e.target.value as keyof typeof providers)}>{Object.entries(providers).map(([id,p])=><option key={id} value={id}>{p.label}</option>)}</select></label><label>选择模型{provider==="custom"?<input value={customModel} onChange={e=>setCustomModel(e.target.value)} placeholder="例如 my-vision-model"/>:<select value={model} onChange={e=>setModel(e.target.value)}>{providers[provider].models.map(m=><option key={m}>{m}</option>)}</select>}</label><label>API 地址<input value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} placeholder="https://api.example.com/v1"/></label><label>API Key<div className="key-input"><input type={showKey?"text":"password"} value={key} onChange={e=>setKey(e.target.value)} autoComplete="off" placeholder="在此粘贴 API Key"/><button onClick={()=>setShowKey(v=>!v)}>{showKey?"隐藏":"显示"}</button></div><small>请勿在聊天、文档或截图中分享密钥。</small></label><footer><button onClick={()=>setAdding(false)}>取消</button><button className="primary" disabled={saving||!key.trim()||!(provider==="custom"?customModel:model)} onClick={()=>void add()}>{saving?"正在保存…":"添加模型"}</button></footer></section></div>}</div>
}
