"use client";

import { useEffect, useMemo, useRef, useState, type Dispatch, type SetStateAction } from "react";
import katex from "katex";
import "katex/dist/katex.min.css";

type View = "home" | "upload" | "cards" | "cardDetail" | "studySelect" | "study" | "stats" | "diary" | "settings";
type Rating = "again" | "hard" | "good" | "easy";
type StudyMode = "quick" | "question";
type ModelConfig = { id:string; provider:string; providerLabel:string; model:string; apiKey?:string; keyLast4?:string; baseUrl:string; enabled:boolean; isDefault:boolean; validationStatus:"pending"|"valid"|"invalid"; validationError?:string|null; lastValidatedAt?:string|null };
type ModelChoice = ModelConfig & { choiceId:string };
type GoogleModel = { id:string; name:string; description:string; inputTokenLimit:number|null; outputTokenLimit:number|null };
type Card = { id:number|string; type:string; front:string; back:string; path:string; tags:string[]; interval:string; tone:string; createdAt?:string|Date|null; lastReviewAt?:string|Date|null; nextReviewAt?:string|Date|null; memoryStatus?:string; sourceUrl?:string|null; detail?:{stem:string;options:string[];answer:string;solution:string;thinkingModel:{name:string;description:string;steps:string[]}|null}|null };
type AnalyzedQuestion = { order:number; questionNumber:string; stem:string; options:string[]; answer:string; solution:string; knowledgePoints:{name:string;summary:string}[]; thinkingModel:{name:string;description:string;steps:string[]}; difficulty:number; confirmed?:boolean; tags?:string[] };
type Tag = { id:string; name:string; count:number };
type DiaryEntry = { id:string; entryDate:string; title:string; content:string; createdAt:string; updatedAt:string };
type StatsData = {totalCards:number;dueCount:number;newToday:number;completedToday:number;streak:number;recent30:number;retention:number;mastered:number;masteredRate:number;trend:{date:string;label:string;count:number}[]};
type RecallScore = {score:number;rating:Rating;summary:string;correctPoints:string[];missingPoints:string[];incorrectPoints:string[];suggestion:string;referenceAnswer:string;keyPoints:string[]};
let diarySessionCache:DiaryEntry[]|null=null;
const emptyStats:StatsData={totalCards:0,dueCount:0,newToday:0,completedToday:0,streak:0,recent30:0,retention:0,mastered:0,masteredRate:0,trend:[]};

function MathText({children,className=""}:{children:string;className?:string}){
  const parts=String(children||"").split(/(\$\$[\s\S]+?\$\$|\\\[[\s\S]+?\\\]|\\\([\s\S]+?\\\)|\$[^$\n]+?\$)/g);
  return <span className={`math-text ${className}`}>{parts.map((part,index)=>{const display=(part.startsWith("$$")&&part.endsWith("$$"))||(part.startsWith("\\[")&&part.endsWith("\\]"));const inline=(part.startsWith("$")&&part.endsWith("$"))||(part.startsWith("\\(")&&part.endsWith("\\)"));if(!display&&!inline)return <span key={index}>{part}</span>;const latex=part.replace(/^\$\$|\$\$$/g,"").replace(/^\$|\$$/g,"").replace(/^\\\[|\\\]$/g,"").replace(/^\\\(|\\\)$/g,"");return <span key={index} className={display?"math-display":"math-inline"} dangerouslySetInnerHTML={{__html:katex.renderToString(latex,{displayMode:display,throwOnError:false,strict:false})}}/>})}</span>
}

function StructuredText({children}:{children:string}){
  const prepared=String(children||"").replace(/\r/g,"").replace(/([^\n])(?=(?:答案|解析|思路|关键|结论|步骤\s*\d*)\s*[:：])/g,"$1\n").replace(/([^\n])(?=\d+[.、]\s*)/g,"$1\n");const lines=prepared.split(/\n+/).map(line=>line.trim()).filter(Boolean);
  return <div className="structured-text">{lines.map((line,index)=>{const heading=line.match(/^(答案|解析|思路|关键|结论|步骤\s*\d*)\s*[:：]\s*(.*)$/);if(heading)return <section className={`structured-section ${heading[1]==="答案"||heading[1]==="结论"?"highlight":""}`} key={index}><strong>{heading[1]}</strong>{heading[2]&&<p><MathText>{heading[2]}</MathText></p>}</section>;const step=line.match(/^(\d+)[.、]\s*(.*)$/);if(step)return <div className="structured-step" key={index}><b>{step[1]}</b><p><MathText>{step[2]}</MathText></p></div>;return <p key={index}><MathText>{line}</MathText></p>})}</div>
}

function fileToDataUrl(file:Blob){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file)})}
async function prepareStoredImage(file:File){
  const objectUrl=URL.createObjectURL(file);try{const image=new Image();image.src=objectUrl;await image.decode();const width=image.naturalWidth;const height=image.naturalHeight;const scale=Math.min(1,2560/Math.max(width,height));if(file.size<=500*1024&&scale===1)return {dataUrl:await fileToDataUrl(file),name:file.name,width,height,compressed:false};const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(width*scale));canvas.height=Math.max(1,Math.round(height*scale));canvas.getContext("2d")?.drawImage(image,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/webp",.9));const selected=blob&&blob.size<file.size?blob:file;return {dataUrl:await fileToDataUrl(selected),name:selected===file?file.name:file.name.replace(/\.[^.]+$/,"")+".webp",width:selected===file?width:canvas.width,height:selected===file?height:canvas.height,compressed:selected!==file}}finally{URL.revokeObjectURL(objectUrl)}
}
function StoredImage({src,alt,className=""}:{src:string;alt:string;className?:string}){
  const [objectUrl,setObjectUrl]=useState("");const [failed,setFailed]=useState(false);
  useEffect(()=>{let disposed=false;let current="";setFailed(false);setObjectUrl("");void fetch(src,{credentials:"include",cache:"force-cache"}).then(response=>{if(!response.ok)throw new Error(`图片读取失败 (${response.status})`);return response.blob()}).then(blob=>{if(disposed)return;current=URL.createObjectURL(blob);setObjectUrl(current)}).catch(()=>{if(!disposed)setFailed(true)});return()=>{disposed=true;if(current)URL.revokeObjectURL(current)}},[src]);
  if(failed)return <div className="missing-source">图片暂时无法读取，请刷新后重试</div>;if(!objectUrl)return <div className="image-loading">正在加载图片…</div>;return <img className={className} src={objectUrl} alt={alt}/>;
}

function questionFront(question:AnalyzedQuestion){const stem=question.stem.trim();const compact=stem.replace(/\s+/g,"");const missing=question.options.filter(option=>!compact.includes(option.replace(/\s+/g,"")));return [stem,...missing].filter(Boolean).join("\n")}
function isAnswerOption(option:string,index:number,answer:string){const letter=String.fromCharCode(65+index);const normalizedAnswer=String(answer||"").trim().toUpperCase();const normalizedOption=String(option||"").trim().toUpperCase();const optionValue=normalizedOption.replace(/^\s*[（(]?\s*[A-Z]\s*[)）.、:]?\s*/,"");if(new RegExp(`(^|[^A-Z])${letter}([^A-Z]|$)`).test(normalizedAnswer))return true;const answerValue=normalizedAnswer.replace(/^(答案|正确答案|选项)\s*[:：]?\s*/,"").replace(/^\s*[（(]?\s*[A-Z]\s*[)）.、:]?\s*/,"").trim();return !!answerValue&&answerValue===optionValue}
function formatCardTime(value?:string|Date|null){if(!value)return "尚未学习";const date=new Date(value);if(Number.isNaN(date.getTime()))return "—";return new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(date)}
function splitCardFront(card:Card){
  const detailOptions=card.detail?.options?.filter(Boolean)||[];const lines=String(card.front||"").split(/\n+/).map(line=>line.trim()).filter(Boolean);const optionPattern=/^[（(]?\s*[A-Z]\s*[)）.、:]\s*/i;const detected=lines.filter(line=>optionPattern.test(line));const options=detailOptions.length?detailOptions:detected;const stem=card.detail?.stem?.trim()||lines.filter(line=>!detected.includes(line)).join("\n")||card.front;
  const lengths=options.map(option=>option.replace(optionPattern,"").replace(/\s+/g,"").length);const shortest=lengths.length?Math.max(1,Math.min(...lengths)):1;const longest=lengths.length?Math.max(...lengths):0;const compact=options.length>=2&&options.length<=6&&longest<=12&&longest/shortest<=3;
  return {stem,options,compact};
}
function CardQuestionPreview({card}:{card:Card}){const {stem,options,compact}=splitCardFront(card);return <div className="card-question-preview"><h3><MathText>{stem}</MathText></h3>{options.length>0&&<div className={`card-preview-options ${compact?"compact":"stacked"}`}>{options.map((option,index)=><span key={`${option}-${index}`}><MathText>{option}</MathText></span>)}</div>}</div>}

const nav = [
  ["home", "首页", "◈"], ["upload", "上传学习内容", "↑"], ["cards", "学习卡片", "▱"], ["stats", "学习统计", "⌑"], ["diary", "悟道日记", "▦"], ["settings", "设置", "⚙"],
] as const;

export default function Home() {
  const [view, setView] = useState<View>("home");
  const [sidebarCollapsed,setSidebarCollapsed]=useState(false);
  const [studyIndex, setStudyIndex] = useState(0);
  const [studyQueue,setStudyQueue]=useState<Array<string|number>>([]);
  const [studyMode,setStudyMode]=useState<StudyMode>("quick");
  const [revealed, setRevealed] = useState(false);
  const [query, setQuery] = useState("");
  const [uploadMode, setUploadMode] = useState<"memorization" | "question" | null>(null);
  const [notice, setNotice] = useState("");
  const [modelConfigs,setModelConfigs]=useState<ModelConfig[]>([]);
  const [modelChoices,setModelChoices]=useState<ModelChoice[]>([]);
  const [selectedModelId,setSelectedModelId]=useState("");
  const [generatedCards,setGeneratedCards]=useState<Card[]>([]);
  const [libraryTags,setLibraryTags]=useState<Tag[]>([]);
  const [statsData,setStatsData]=useState<StatsData>(emptyStats);
  const [selectedCard,setSelectedCard]=useState<Card|null>(null);
  const allCards=generatedCards;
  const dueCards = allCards.filter(card=>card.memoryStatus!=="mastered"&&(!card.nextReviewAt||new Date(card.nextReviewAt)<=new Date()));
  const activeCard = studyQueue.length?allCards.find(card=>card.id===studyQueue[studyIndex]):undefined;
  const filtered = useMemo(() => allCards.filter(c => `${c.front}${c.tags.join("")}${c.path}`.toLowerCase().includes(query.toLowerCase())), [query,allCards]);
  const activeModel=modelChoices.find(c=>c.choiceId===selectedModelId)||modelChoices.find(c=>c.isDefault&&c.model===modelConfigs.find(config=>config.id===c.id)?.model)||modelChoices[0];

  useEffect(()=>{let cancelled=false;fetch("/api/models").then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||"读取模型配置失败");if(!cancelled)setModelConfigs(data.configs||[])}).catch(error=>{if(!cancelled)setNotice(error instanceof Error?error.message:"读取模型配置失败")});return()=>{cancelled=true}},[]);
  useEffect(()=>{let cancelled=false;const valid=modelConfigs.filter(config=>config.enabled&&config.validationStatus==="valid");if(!valid.length){setModelChoices([]);return}Promise.all(valid.map(async config=>{try{const response=await fetch("/api/models/discover",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({configId:config.id})});const data=await response.json();if(!response.ok)throw new Error(data.error);const ids=[...new Set<string>((data.models||[]).map((item:GoogleModel)=>item.id).filter(Boolean))];return (ids.length?ids:[config.model]).map(model=>({...config,model,choiceId:`${config.id}::${model}`}))}catch{return [{...config,choiceId:`${config.id}::${config.model}`}]}})).then(groups=>{if(!cancelled)setModelChoices(groups.flat())});return()=>{cancelled=true}},[modelConfigs]);
  useEffect(()=>{let cancelled=false;fetch("/api/cards").then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||"读取卡片失败");if(!cancelled){setGeneratedCards(data.cards||[]);setLibraryTags(data.tags||[])}}).catch(()=>{});return()=>{cancelled=true}},[]);
  useEffect(()=>{let cancelled=false;fetch("/api/stats").then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||"读取统计失败");if(!cancelled)setStatsData(data)}).catch(()=>{});return()=>{cancelled=true}},[]);
  useEffect(()=>{setSidebarCollapsed(window.localStorage.getItem("learner-sidebar-collapsed")==="1")},[]);
  function toggleSidebar(){setSidebarCollapsed(current=>{const next=!current;window.localStorage.setItem("learner-sidebar-collapsed",next?"1":"0");return next})}

  async function startStudy(mode:StudyMode){setNotice("");setStudyMode(mode);try{const response=await fetch("/api/cards");const data=await response.json();if(!response.ok)throw new Error(data.error||"读取到期卡片失败");const fresh:Card[]=data.cards||[];const due=fresh.filter(card=>card.memoryStatus!=="mastered"&&(!card.nextReviewAt||new Date(card.nextReviewAt)<=new Date()));setGeneratedCards(fresh);setLibraryTags(data.tags||[]);setStudyQueue(due.map(card=>card.id));setStudyIndex(0);setRevealed(false);setView("study")}catch(error){setNotice(error instanceof Error?error.message:"读取到期卡片失败")}}

  async function rate(rating: Rating) {
    if(!activeCard)return;try{const response=await fetch("/api/reviews",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({cardId:activeCard.id,rating})});const data=await response.json();if(!response.ok)throw new Error(data.error||"保存学习记录失败");setGeneratedCards(cards=>cards.map(card=>card.id===activeCard.id?{...card,lastReviewAt:data.lastReviewAt,nextReviewAt:data.nextReviewAt,memoryStatus:data.status,interval:`${data.intervalDays} 天`}:card));const statsResponse=await fetch("/api/stats");if(statsResponse.ok)setStatsData(await statsResponse.json());setNotice(`已记录 · ${data.intervalDays} 天后复习`);setTimeout(() => { setStudyIndex(index=>index+1); setRevealed(false); setNotice(""); }, 650)}catch(error){setNotice(error instanceof Error?error.message:"保存学习记录失败")}
  }

  return (
    <main className="app-shell">
      <aside className={`sidebar ${sidebarCollapsed?"collapsed":""}`}>
        <div className="brand-row"><button className="brand" onClick={() => setView("home")}><span className="brand-mark">悟</span><span>悟道</span></button><button className="sidebar-toggle" onClick={toggleSidebar} aria-label={sidebarCollapsed?"展开菜单栏":"收起菜单栏"} title={sidebarCollapsed?"展开菜单栏":"收起菜单栏"}>{sidebarCollapsed?"›":"‹"}</button></div>
        <nav>{nav.map(([id, label, icon]) => <button key={id} className={view === id||(id==="cards"&&view==="cardDetail") ? "active" : ""} onClick={() => setView(id as View)}><i>{icon}</i>{label}{id === "cards" && <b>{allCards.length}</b>}</button>)}</nav>
        <div className="sidebar-card"><span>连续学习</span><strong>{statsData.streak} <small>天</small></strong><div className="week">{statsData.trend.slice(-7).map(item=><i className={item.count?"done":""} key={item.date}>{item.count?"✓":item.label.split("/")[1]}</i>)}</div></div>
        <button className="profile"><span>林</span><span>林晓宇<small>学习设置</small></span><i>···</i></button>
      </aside>

      <section className={`workspace ${sidebarCollapsed?"sidebar-collapsed":""}`}>
        <header className="topbar"><div className="mobile-logo">悟道</div><button className="search" onClick={() => setView("cards")}><span>⌕</span>搜索卡片、标签或目录 <kbd>⌘ K</kbd></button><div className="top-actions"><button>○</button><button>♧</button><span className="avatar">林</span></div></header>

        {view === "home" && <Dashboard onStudy={()=>setView("studySelect")} onUpload={() => setView("upload")} onCards={() => setView("cards")} stats={statsData} cards={allCards} />}
        {view === "cards" && <CardLibrary cards={filtered} tags={libraryTags} query={query} setQuery={setQuery} dueCount={statsData.dueCount} onStudy={()=>setView("studySelect")} onOpenDetail={card=>{setSelectedCard(card);setView("cardDetail")}} />}
        {view === "cardDetail" && selectedCard && <CardDetail card={selectedCard} onClose={()=>setView("cards")} onDeleted={()=>{setGeneratedCards(items=>items.filter(card=>card.id!==selectedCard.id));setSelectedCard(null);setView("cards")}}/>}
        <div className="persistent-upload-workspace" hidden={view!=="upload"}><AIUpload active={view==="upload"} mode={uploadMode} setMode={setUploadMode} model={activeModel} models={modelChoices} onModelChange={setSelectedModelId} onCardsGenerated={newCards=>{setGeneratedCards(prev=>[...newCards,...prev]);setView("cards")}} /></div>
        {view === "studySelect" && <StudyModeSelect dueCount={statsData.dueCount} onSelect={mode=>void startStudy(mode)} onClose={()=>setView("cards")}/>}
        {view === "study" && <Study mode={studyMode} card={activeCard} model={activeModel} revealed={revealed} setRevealed={setRevealed} rate={rate} current={Math.min(studyIndex+1,studyQueue.length)} total={studyQueue.length} notice={notice} onExit={() => setView("home")} />}
        {view === "stats" && <Stats stats={statsData} />}
        {view === "diary" && <Diary />}
        {view === "settings" && <Settings configs={modelConfigs} setConfigs={setModelConfigs} />}
      </section>
    </main>
  );
}

function Dashboard({onStudy,onUpload,onCards,stats,cards}:{onStudy:()=>void;onUpload:()=>void;onCards:()=>void;stats:StatsData;cards:Card[]}) {
  const [dateLabel,setDateLabel]=useState("");
  useEffect(()=>{setDateLabel(new Intl.DateTimeFormat("zh-CN",{weekday:"long",month:"long",day:"numeric"}).format(new Date()))},[]);
  return <div className="page dashboard"><div className="eyebrow">{dateLabel||" "}</div><h1>欢迎回来 <span>✦</span></h1><p className="lead">今天也来让知识留下来。</p>
    <section className="hero-card"><div className="hero-copy"><div className="hero-label"><i></i>今日学习</div><div className="hero-num">{stats.dueCount} <small>张待复习</small></div><p>知识库共 {stats.totalCards} 张卡片，今日已完成 {stats.completedToday} 次复习</p><button className="primary light" disabled={!stats.totalCards} onClick={onStudy}>开始学习 <span>→</span></button></div><div className="orbit"><span className="orb one">{stats.streak}天</span><span className="orb two">{stats.retention}%</span><span className="orb three">{stats.newToday}新</span><span className="orb four">{stats.mastered}</span><div className="rings"></div></div></section>
    <div className="metrics"><article><span className="metric-icon orange">◷</span><div><small>待复习</small><strong>{stats.dueCount}</strong></div><em>共 {stats.totalCards} 张</em></article><article><span className="metric-icon blue">+</span><div><small>今日新卡</small><strong>{stats.newToday}</strong></div><em>来自生产库</em></article><article><span className="metric-icon green">✓</span><div><small>今日已完成</small><strong>{stats.completedToday}</strong></div><em>连续 {stats.streak} 天</em></article></div>
    <div className="section-title"><div><h2>最近创建</h2><p>继续处理生产库中的学习卡片</p></div><button onClick={onCards}>查看全部 →</button></div>
    {cards.length?<div className="recent-grid">{cards.slice(0,2).map((card,index)=><article className={`recent ${index?"violet-border":"orange-border"}`} key={card.id}><div><span>{card.type}</span><b>{formatCardTime(card.createdAt)}</b></div><h3><MathText>{card.detail?.stem||card.front}</MathText></h3><p>最近学习：{formatCardTime(card.lastReviewAt)}</p></article>)}</div>:<div className="empty-card-results"><strong>还没有学习卡片</strong><p>上传学习内容后，真实卡片会显示在这里。</p></div>}
    <section className="create-panel"><div className="spark">✦</div><div><h2>把新知识变成长期记忆</h2><p>上传截图或照片，AI 会拆分知识、解题并生成学习卡片。</p></div><button className="primary" onClick={onUpload}>↑ 上传学习内容</button></section>
  </div>;
}

function CardLibrary({cards:items,tags:allTags,query,setQuery,dueCount,onStudy,onOpenDetail}:{cards:Card[];tags:Tag[];query:string;setQuery:(v:string)=>void;dueCount:number;onStudy:()=>void;onOpenDetail:(card:Card)=>void}) {
  const [tagQuery,setTagQuery]=useState("");const [selectedTags,setSelectedTags]=useState<string[]>([]);
  const visibleTags=allTags.filter(tag=>tag.name.toLocaleLowerCase().includes(tagQuery.trim().toLocaleLowerCase()));const shown=selectedTags.length?items.filter(card=>selectedTags.every(selectedTag=>card.tags.some(tag=>tag.toLocaleLowerCase()===selectedTag.toLocaleLowerCase()))):items;
  function toggleTag(name:string){setSelectedTags(current=>current.includes(name)?current.filter(tag=>tag!==name):[...current,name])}
  return <div className="page"><div className="page-heading"><div><span className="eyebrow">知识库</span><h1>学习卡片</h1><p>{shown.length} 张生产卡片，每一张都可回溯原始资料。</p></div><button className="primary" disabled={!items.length} onClick={onStudy}>▶ 学习到期卡片</button></div><div className="library-tools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索卡片、标签或目录…"/><button>全部类型 ⌄</button><button>今日待复习</button></div><div className="library-layout"><aside className="tag-sidebar"><header><strong>标签</strong>{selectedTags.length>0&&<button onClick={()=>setSelectedTags([])}>清空</button>}</header><input value={tagQuery} onChange={event=>setTagQuery(event.target.value)} placeholder="搜索标签…"/><nav><button className={selectedTags.length===0?"active":""} onClick={()=>setSelectedTags([])}><span>全部标签</span><b>{items.length}</b></button>{visibleTags.map(tag=><button key={tag.id} className={selectedTags.includes(tag.name)?"active":""} onClick={()=>toggleTag(tag.name)}><span>#{tag.name}</span><b>{items.filter(card=>card.tags.some(name=>name.toLocaleLowerCase()===tag.name.toLocaleLowerCase())).length}</b></button>)}</nav></aside><section className="filtered-cards">{selectedTags.length>0&&<div className="active-tag-filters"><small>已选标签</small>{selectedTags.map(tag=><button key={tag} onClick={()=>toggleTag(tag)}>#{tag} ×</button>)}</div>}<div className="card-list">{shown.map(card=><article className="knowledge-card" key={card.id}><div className="card-body"><div className="card-meta-row"><div><span className={`type-pill ${card.tone}`}>{card.type}</span><span className="path">{card.path}</span></div><div className="card-time-badges"><span><small>创建</small>{formatCardTime(card.createdAt)}</span><span><small>最近学习</small>{formatCardTime(card.lastReviewAt)}</span></div></div><CardQuestionPreview card={card}/><div className="tags">{card.tags.map(tag=><span key={tag}>#{tag}</span>)}</div></div><div className="due"><small>下次复习</small><strong>{card.interval}</strong><button className="detail-trigger" onClick={()=>onOpenDetail(card)}>查看详情</button></div></article>)}</div>{shown.length===0&&<div className="empty-card-results"><strong>{items.length===0?"生产库中还没有学习卡片":"没有符合当前标签的卡片"}</strong><p>{items.length===0?"上传学习内容并生成卡片后，会在这里显示。":"取消部分标签或选择全部标签。"}</p></div>}</section></div></div>;
}

function CardDetail({card,onClose,onDeleted}:{card:Card;onClose:()=>void;onDeleted:()=>void}){
  const detail=card.detail;const isMemorization=card.type==="背诵";const [deleting,setDeleting]=useState(false);const [deleteError,setDeleteError]=useState("");
  async function remove(){if(typeof card.id!=="string"||!window.confirm("确定删除这张卡片吗？如果原图还关联其他卡片，原图会继续保留。"))return;setDeleting(true);setDeleteError("");try{const response=await fetch(`/api/cards?id=${encodeURIComponent(card.id)}`,{method:"DELETE"});const data=await response.json();if(!response.ok)throw new Error(data.error||"删除失败");onDeleted()}catch(error){setDeleteError(error instanceof Error?error.message:"删除失败")}finally{setDeleting(false)}}
  return <div className={`page card-detail-page${isMemorization?" memorization-detail":""}`}><header><button className="detail-back" onClick={onClose}>← 返回学习卡片</button><div className="card-detail-actions">{typeof card.id==="string"&&<button className="delete-card" disabled={deleting} onClick={()=>void remove()}>{deleting?"删除中…":"删除卡片"}</button>}</div></header><div className="detail-page-heading"><span className="eyebrow">学习卡片详情</span><h1>{card.type}</h1><p>查看原始资料、题目解析与可迁移的思维模型。</p></div>{deleteError&&<div className="upload-message error">! {deleteError}</div>}{isMemorization?<main className="memorization-detail-flow"><section><small>题目</small><MathText>{detail?.stem||card.front}</MathText></section><section className="memorization-source"><small>上传的原图</small>{card.sourceUrl?<StoredImage src={card.sourceUrl} alt="卡片原始上传图片"/>:<div className="missing-source">该历史卡片未保存原图</div>}</section><section className="solution-panel"><small>分步解析</small><StructuredText>{detail?.solution||card.back}</StructuredText></section>{detail?.thinkingModel&&<section className="detail-thinking"><small>思维模型</small><h3>{detail.thinkingModel.name}</h3><MathText>{detail.thinkingModel.description}</MathText><ol>{detail.thinkingModel.steps.map(step=><li key={step}><MathText>{step}</MathText></li>)}</ol></section>}<section><small>标签</small><div className="tags">{card.tags.map(tag=><span key={tag}>#{tag}</span>)}</div></section></main>:<div className="card-detail-grid"><main className="detail-left"><section><small>上传的原图</small>{card.sourceUrl?<StoredImage src={card.sourceUrl} alt="卡片原始上传图片"/>:<div className="missing-source">该历史卡片未保存原图</div>}</section><section><small>题目</small><MathText>{detail?.stem||card.front}</MathText></section>{detail?.options?.length?<section><small>选项</small><div className="detail-options">{detail.options.map((option,index)=><span className={isAnswerOption(option,index,detail.answer)?"correct-option":""} key={index}><MathText>{option}</MathText>{isAnswerOption(option,index,detail.answer)&&<b>正确答案</b>}</span>)}</div></section>:null}<section><small>标签</small><div className="tags">{card.tags.map(tag=><span key={tag}>#{tag}</span>)}</div></section></main><aside className="detail-right"><section className="solution-panel"><small>分步解析</small><StructuredText>{detail?.solution||card.back}</StructuredText></section>{detail?.thinkingModel&&<section className="detail-thinking"><small>思维模型</small><h3>{detail.thinkingModel.name}</h3><MathText>{detail.thinkingModel.description}</MathText><ol>{detail.thinkingModel.steps.map(step=><li key={step}><MathText>{step}</MathText></li>)}</ol></section>}</aside></div>}</div>
}

function Upload({mode,setMode}:{mode:"memorization"|"question"|null;setMode:(m:"memorization"|"question")=>void}) {
  const [file,setFile]=useState<File|null>(null); const [preview,setPreview]=useState(""); const [dragging,setDragging]=useState(false); const [message,setMessage]=useState("");
  function acceptImage(next?:File){if(!next)return;if(!next.type.startsWith("image/")){setMessage("请选择图片文件");return}setFile(next);setMessage("")}
  useEffect(()=>{if(!file){setPreview("");return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);
  useEffect(()=>{function onPaste(event:ClipboardEvent){const image=Array.from(event.clipboardData?.items||[]).find(item=>item.type.startsWith("image/"))?.getAsFile();if(image){event.preventDefault();acceptImage(new File([image],`clipboard-${Date.now()}.${image.type.split("/")[1]||"png"}`,{type:image.type}));setMessage("已从剪贴板粘贴图片")}}window.addEventListener("paste",onPaste);return()=>window.removeEventListener("paste",onPaste)},[]);
  return <div className="page upload-page"><div className="page-heading"><div><span className="eyebrow">AI 学习助手</span><h1>上传学习内容</h1><p>拖拽、点击选择，或直接粘贴截图，让 AI 把它变成可以长期复习的卡片。</p></div></div><div className="upload-layout"><section><div className={`dropzone ${file?"has-file":""} ${dragging?"dragging":""}`} onDragEnter={e=>{e.preventDefault();setDragging(true)}} onDragOver={e=>e.preventDefault()} onDragLeave={e=>{e.preventDefault();setDragging(false)}} onDrop={e=>{e.preventDefault();setDragging(false);acceptImage(e.dataTransfer.files[0])}}><input aria-label="选择图片" type="file" accept="image/*" onChange={e=>acceptImage(e.target.files?.[0])}/>{preview?<><img className="upload-preview" src={preview} alt="待上传图片预览"/><button className="remove-upload" onClick={e=>{e.preventDefault();e.stopPropagation();setFile(null);setMessage("")}} aria-label="移除图片">×</button><div className="file-summary"><strong>{file?.name}</strong><span>{file?`${(file.size/1024/1024).toFixed(2)} MB · ${file.type.replace("image/","").toUpperCase()}`:""}</span></div></>:<><div className="upload-icon">↑</div><h2>{dragging?"松手即可添加图片":"拖拽图片到这里"}</h2><p>点击选择，或按 <kbd>⌘ V</kbd> / <kbd>Ctrl V</kbd> 粘贴截图</p><div className="format-hint">PNG、JPG、WEBP</div></>}</div>{message&&<div className={`upload-message ${file?"success":"error"}`}>{file?"✓":"!"} {message}</div>}<h3 className="mode-title">你希望如何处理这份资料？</h3><div className="mode-grid"><button className={mode==="memorization"?"selected":""} onClick={()=>setMode("memorization")}><i>◇</i><strong>背诵内容</strong><span>提取独立知识点，自动生成问题与答案</span></button><button className={mode==="question"?"selected":""} onClick={()=>setMode("question")}><i>∑</i><strong>题目模式</strong><span>识别并拆题，生成答案、解析与思维模型</span></button></div><button className="primary wide" disabled={!file||!mode}>{file&&mode?"开始 AI 解析 →":"请先上传图片并选择模式"}</button></section><aside className="pipeline"><h3>解析流程</h3>{["图片识别与内容拆分","逐项 AI 理解与生成","你审核、修改 AI 结果","选择并生成学习卡片"].map((x,i)=><div key={x}><b>{i+1}</b><span>{x}<small>{i===2?"结果不会自动入库":""}</small></span></div>)}<p>✦ 原始资料会永久保留，每张卡片都可回溯来源。</p></aside></div></div>
}

function AIUpload({active,mode,setMode,model,models,onModelChange,onCardsGenerated}:{active:boolean;mode:"memorization"|"question"|null;setMode:(m:"memorization"|"question")=>void;model?:ModelChoice;models:ModelChoice[];onModelChange:(id:string)=>void;onCardsGenerated:(cards:Card[])=>void}){
  const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState("");const [dragging,setDragging]=useState(false);const [phase,setPhase]=useState<"upload"|"analyzing"|"review">("upload");const [progress,setProgress]=useState(0);const [questions,setQuestions]=useState<AnalyzedQuestion[]>([]);const [error,setError]=useState("");const [preparingImage,setPreparingImage]=useState(false);const [generating,setGenerating]=useState(false);const generatingRef=useRef(false);const generationKeyRef=useRef("");const preparedImageRef=useRef<Promise<Awaited<ReturnType<typeof prepareStoredImage>>|null>|null>(null);
  function acceptImage(next?:File){if(!next)return;if(!next.type.startsWith("image/")){setError("请上传图片文件");return}setFile(next);setError("");setQuestions([]);setPhase("upload");generationKeyRef.current=crypto.randomUUID();preparedImageRef.current=null;setPreparingImage(false);generatingRef.current=false;setGenerating(false)}
  useEffect(()=>{if(!file){setPreview("");return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);
  useEffect(()=>{if(!active)return;function paste(e:ClipboardEvent){const image=Array.from(e.clipboardData?.items||[]).find(i=>i.type.startsWith("image/"))?.getAsFile();if(image){e.preventDefault();acceptImage(image)}}window.addEventListener("paste",paste);return()=>window.removeEventListener("paste",paste)},[active]);
  async function analyze(){if(!file||!mode||!model)return;setPhase("analyzing");setError("");setProgress(12);setPreparingImage(true);preparedImageRef.current=prepareStoredImage(file).catch(()=>null).finally(()=>setPreparingImage(false));if(!generationKeyRef.current)generationKeyRef.current=crypto.randomUUID();const timer=setInterval(()=>setProgress(v=>Math.min(v+Math.ceil(Math.random()*8),88)),700);try{const dataUrl=await fileToDataUrl(file);const response=await fetch("/api/ai/analyze",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({image:dataUrl,mode,modelConfigId:model.id,provider:model.provider,model:model.model,baseUrl:model.baseUrl})});const data=await response.json();if(!response.ok)throw new Error(data.error||"AI 解析失败");const analyzed=(data.questions||[]).map((q:AnalyzedQuestion)=>({...q,confirmed:false,tags:[...new Set((q.knowledgePoints||[]).map(point=>point.name).filter(Boolean))]}));setQuestions(mode==="memorization"?analyzed.slice(0,1):analyzed);setProgress(100);setTimeout(()=>setPhase("review"),350)}catch(e){setError(e instanceof Error?e.message:"解析失败");setPhase("upload")}finally{clearInterval(timer)}}
  function updateQuestion(index:number,patch:Partial<AnalyzedQuestion>){setQuestions(items=>items.map((q,i)=>i===index?{...q,...patch}:q))}
  async function generateCards(){if(generatingRef.current)return;generatingRef.current=true;setGenerating(true);setError("");const drafts=questions.filter(q=>q.confirmed).map(q=>({cardType:mode==="memorization"?"memorization":"question",front:questionFront(q),back:mode==="memorization"?q.answer:`答案：${q.answer}\n\n解析：${q.solution}`,stem:q.stem,options:q.options,answer:q.answer,solution:q.solution,thinkingModel:q.thinkingModel,tags:q.tags||[]}));try{const stored=file?await (preparedImageRef.current||prepareStoredImage(file)):null;if(file&&!stored)throw new Error("图片优化失败，请重新选择图片后重试");const response=await fetch("/api/cards",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({generationKey:generationKeyRef.current||crypto.randomUUID(),cards:drafts,sourceImage:stored?.dataUrl||null,sourceName:stored?.name||file?.name,sourceWidth:stored?.width,sourceHeight:stored?.height})});const data=await response.json();if(!response.ok)throw new Error(data.error||"保存卡片失败");onCardsGenerated(data.cards||[])}catch(e){setError(e instanceof Error?e.message:"保存卡片失败");generatingRef.current=false;setGenerating(false)}}
  if(phase==="analyzing")return <div className="page analysis-page"><div className="analysis-loader"><div className="scan-art"><img src={preview} alt="正在解析"/><i style={{top:`${Math.min(progress,92)}%`}}></i></div><span className="eyebrow">AI PIPELINE</span><h1>{mode==="memorization"?"正在提炼背诵要点…":"正在识别并拆分题目…"}</h1><p>{mode==="memorization"?(progress<35?"识别图片中的核心知识":progress<65?"生成回忆问题与精炼答案":"总结背诵技巧、关键词和应用场景"):(progress<35?"识别题目边界与公式":progress<65?"逐题生成答案与解析":"提炼知识点和可迁移思维模型")}</p><div className="analysis-progress"><i style={{width:`${progress}%`}}></i></div><b>{progress}%</b><small>请不要关闭页面，复杂内容可能需要几十秒</small></div></div>;
  if(phase==="review")return <div className="page review-page"><div className="review-heading"><div><span className="eyebrow">AI 解析完成</span><h1>{mode==="memorization"?"已生成 1 个总问题":`识别到 ${questions.length} 道题`}</h1><p>{mode==="memorization"?"请审核卡片正面问题；卡片答案将直接显示上传的原图。":"请逐题审核。数学公式已自动排版，需要时可点击编辑。"}</p></div><button className="secondary" disabled={generating} onClick={()=>setPhase("upload")}>重新上传</button></div>{error&&<div className="upload-message error">! {error}</div>}<div className="review-list">{questions.map((q,index)=><QuestionReview key={index} question={q} index={index} memorization={mode==="memorization"} onUpdate={patch=>updateQuestion(index,patch)}/>)}</div><div className="review-footer"><span>已确认 {questions.filter(q=>q.confirmed).length} / {questions.length} {mode==="memorization"?"张":"道题"}{preparingImage?" · 正在优化图片":" · 图片已准备"}</span><button className="primary" disabled={generating||preparingImage||!questions.some(q=>q.confirmed)} onClick={()=>void generateCards()}>{generating?"正在保存，请勿重复点击…":`生成 ${questions.filter(q=>q.confirmed).length} 张${mode==="memorization"?"背诵":"学习"}卡片 →`}</button></div></div>;
  const pipeline=mode==="memorization"?["识别整张图片内容","生成一个总问题","答案直接使用原图","确认后生成一张背诵卡片"]:["识别题目数量并拆分","逐题生成答案与解析","总结知识点与思维模型","人工确认后生成多张卡片"];
  return <div className="page upload-page"><div className="page-heading"><div><span className="eyebrow">AI 学习助手</span><h1>上传学习内容</h1><p>拖拽、点击选择，或直接粘贴截图。</p></div>{models.length?<label className="active-model model-quick-select"><span>✦ 快速切换模型</span><select aria-label="选择 AI 模型" value={model?.choiceId||""} onChange={e=>onModelChange(e.target.value)}>{models.map(item=><option value={item.choiceId} key={item.choiceId}>{item.providerLabel} · {item.model}</option>)}</select><small>显示已验证厂商 Key 可用的全部模型</small></label>:<div className="active-model model-unavailable"><strong>暂无可用模型</strong><span>请先在设置中添加并验证 API Key</span></div>}</div><div className="upload-layout"><section><div className={`dropzone ${file?"has-file":""} ${dragging?"dragging":""}`} onDragEnter={e=>{e.preventDefault();setDragging(true)}} onDragOver={e=>e.preventDefault()} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);acceptImage(e.dataTransfer.files[0])}}><input aria-label="选择图片" type="file" accept="image/*" onChange={e=>acceptImage(e.target.files?.[0])}/>{preview?<><img className="upload-preview" src={preview} alt="待解析图片"/><button className="remove-upload" onClick={e=>{e.preventDefault();e.stopPropagation();setFile(null)}}>×</button><div className="file-summary"><strong>{file?.name}</strong><span>{file?`${(file.size/1024/1024).toFixed(2)} MB`:""}</span></div></>:<><div className="upload-icon">↑</div><h2>{dragging?"松手即可添加图片":"拖拽图片到这里"}</h2><p>点击选择，或按 <kbd>⌘ V</kbd> / <kbd>Ctrl V</kbd> 粘贴</p></>}</div>{error&&<div className="upload-message error">! {error}</div>}<h3 className="mode-title">你希望如何处理这份资料？</h3><div className="mode-grid"><button className={mode==="memorization"?"selected":""} onClick={()=>setMode("memorization")}><i>◇</i><strong>背诵内容</strong><span>提炼要点，生成问题、记忆技巧与应用场景</span></button><button className={mode==="question"?"selected":""} onClick={()=>setMode("question")}><i>∑</i><strong>题目模式</strong><span>拆题、解答、解析与思维模型</span></button></div><button className="primary wide" disabled={!file||!mode||!model} onClick={analyze}>{!model?"请先在设置中添加并验证模型":file&&mode?"开始 AI 解析 →":"请先上传图片并选择模式"}</button></section><aside className="pipeline"><h3>真实解析流程</h3>{pipeline.map((x,i)=><div key={x}><b>{i+1}</b><span>{x}</span></div>)}</aside></div></div>
}

function QuestionReview({question:q,index,memorization=false,onUpdate}:{question:AnalyzedQuestion;index:number;memorization?:boolean;onUpdate:(patch:Partial<AnalyzedQuestion>)=>void}){
  const [editing,setEditing]=useState(false);
  return <article className={q.confirmed?"confirmed":""}><header><div><b>{memorization?"背诵要点":"题目"} {q.questionNumber||index+1}</b><span>{memorization?"记忆":"题目"}难度 {q.difficulty}/5</span></div><div className="review-actions"><button type="button" onClick={()=>setEditing(value=>!value)}>{editing?"完成编辑":"编辑内容"}</button><label><input type="checkbox" checked={!!q.confirmed} onChange={e=>onUpdate({confirmed:e.target.checked})}/>{q.confirmed?"已确认":"确认无误"}</label></div></header>
    {editing?<><label>原始题目<textarea value={q.stem} onChange={e=>onUpdate({stem:e.target.value})}/></label>{q.options.length>0&&<div className="review-options">{q.options.map((option,i)=><input key={i} value={option} onChange={e=>onUpdate({options:q.options.map((item,j)=>j===i?e.target.value:item)})}/>)}</div>}<div className="review-columns"><label>AI 答案<textarea value={q.answer} onChange={e=>onUpdate({answer:e.target.value})}/></label><label>AI 解析<textarea value={q.solution} onChange={e=>onUpdate({solution:e.target.value})}/></label></div></>:<><section className="rendered-field"><small>原始题目</small><MathText>{q.stem}</MathText></section>{q.options.length>0&&<div className="review-options rendered-options">{q.options.map((option,i)=><span className={isAnswerOption(option,i,q.answer)?"correct-option":""} key={i}><MathText>{option}</MathText>{isAnswerOption(option,i,q.answer)&&<b>AI 答案</b>}</span>)}</div>}<section className="rendered-field solution solution-panel full-solution"><small>AI 分步解析</small><StructuredText>{q.solution}</StructuredText></section></>}
    {editing&&<TagPicker selected={q.tags||[]} onChange={tags=>onUpdate({tags})}/>}<div className="knowledge-row"><div><small>卡片标签</small>{(q.tags||[]).map(tag=><span key={tag}>#{tag}</span>)}</div><div className="thinking-box"><small>思维模型</small><strong>{q.thinkingModel.name}</strong><p><MathText>{q.thinkingModel.description}</MathText></p><ol>{q.thinkingModel.steps.map(step=><li key={step}><MathText>{step}</MathText></li>)}</ol></div></div>
  </article>
}

function TagPicker({selected,onChange}:{selected:string[];onChange:(tags:string[])=>void}){
  const [allTags,setAllTags]=useState<Tag[]>([]);const [query,setQuery]=useState("");const [busy,setBusy]=useState(false);const [tagError,setTagError]=useState("");
  async function load(){try{const response=await fetch("/api/tags");const data=await response.json();if(response.ok)setAllTags(data.tags||[])}catch{}}
  useEffect(()=>{void load();const refresh=()=>void load();window.addEventListener("learner-tags-changed",refresh);return()=>window.removeEventListener("learner-tags-changed",refresh)},[]);
  const normalized=query.trim().replace(/\s+/g," ").toLocaleLowerCase();const matches=allTags.filter(tag=>tag.name.toLocaleLowerCase().includes(normalized)&&!selected.some(name=>name.toLocaleLowerCase()===tag.name.toLocaleLowerCase()));const exact=allTags.find(tag=>tag.name.toLocaleLowerCase()===normalized);
  function add(name:string){if(selected.some(tag=>tag.toLocaleLowerCase()===name.toLocaleLowerCase()))return;onChange([...selected,name]);setQuery("")}
  async function create(){if(!normalized||exact)return exact&&add(exact.name);setBusy(true);setTagError("");try{const response=await fetch("/api/tags",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:query})});const data=await response.json();if(!response.ok)throw new Error(data.error||"创建标签失败");add(data.tag.name);window.dispatchEvent(new Event("learner-tags-changed"))}catch(error){setTagError(error instanceof Error?error.message:"创建标签失败")}finally{setBusy(false)}}
  return <section className="tag-editor"><div className="tag-editor-heading"><div><small>卡片标签</small><strong>搜索已有标签，或创建新标签</strong></div><span>已选 {selected.length} 个</span></div><div className="selected-tags">{selected.map(tag=><button key={tag} onClick={()=>onChange(selected.filter(name=>name!==tag))}>#{tag} ×</button>)}</div><div className="tag-search"><input value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"){event.preventDefault();void create()}}} placeholder="输入标签名称…"/>{normalized&&!exact&&<button disabled={busy} onClick={()=>void create()}>{busy?"创建中…":`+ 创建“${query.trim()}”`}</button>}</div>{normalized&&<div className="tag-results">{matches.map(tag=><button key={tag.id} onClick={()=>add(tag.name)}>#{tag.name}</button>)}{exact&&selected.some(name=>name.toLocaleLowerCase()===normalized)&&<small>该标签已添加，不能重复。</small>}</div>}{tagError&&<p className="tag-error">{tagError}</p>}</section>
}

function StudyModeSelect({dueCount,onSelect,onClose}:{dueCount:number;onSelect:(mode:StudyMode)=>void;onClose:()=>void}){return <div className="study-mode-page"><button className="study-mode-back" onClick={onClose}>← 返回学习卡片</button><div className="study-mode-heading"><span className="eyebrow">今日复习 · {dueCount} 张到期</span><h1>选择学习方式</h1><p>同一批到期卡片，可以训练解题思路，也可以直接检验答案。</p></div><div className="study-mode-grid"><button onClick={()=>onSelect("quick")}><i>↯</i><strong>思路速刷</strong><p>不选择答案，只判断解题思路是否顺畅。选择后立即查看答案与解析。</p><span>通畅 · 阻塞 · 毫无思路 <b>开始 →</b></span></button><button onClick={()=>onSelect("question")}><i>✓</i><strong>做题模式</strong><p>直接选择题目答案，系统会标记对错，并展示正确答案与解析。</p><span>选择答案 · 即时反馈 <b>开始 →</b></span></button></div></div>}

function Study({mode,card,model,revealed,setRevealed,rate,current,total,notice,onExit}:{mode:StudyMode;card?:Card;model?:ModelChoice;revealed:boolean;setRevealed:(v:boolean)=>void;rate:(r:Rating)=>void;current:number;total:number;notice:string;onExit:()=>void}){
  const [rating,setRating]=useState<Rating|null>(null);const [selectedOption,setSelectedOption]=useState<number|null>(null);const [recallScore,setRecallScore]=useState<RecallScore|null>(null);const question=card?splitCardFront(card):null;
  useEffect(()=>{setRating(null);setSelectedOption(null);setRecallScore(null);setRevealed(false)},[card?.id,mode]);
  if(!card)return <div className="study-page"><header><button onClick={onExit}>×</button><div><span>今日学习</span></div><button>···</button></header><div className="study-stage"><div className="empty-card-results"><strong>暂无待复习卡片</strong><p>当前所有卡片都已完成，可以稍后再来。</p><button className="primary" onClick={onExit}>返回首页</button></div></div></div>;
  function chooseThought(next:Rating){setRating(next);setRevealed(true)}
  function chooseOption(index:number){if(revealed)return;setSelectedOption(index);setRating(isAnswerOption(question!.options[index],index,card!.detail?.answer||"")?"good":"again");setRevealed(true)}
  const isRecallQuestion=mode==="question"&&card.type==="背诵";
  return <div className="study-page"><header><button onClick={onExit}>×</button><div><span>{mode==="quick"?"思路速刷":"做题模式"}</span><progress value={current} max={Math.max(total,1)}/><b>{current} / {total}</b></div><button>···</button></header><div className="study-stage"><div className={`flashcard ${revealed?"revealed":""}`}><div className="flash-meta"><span>{card.type}</span><small>{card.path}</small></div><div className="flash-front"><small>问题</small><h2><MathText>{question!.stem}</MathText></h2>{!isRecallQuestion&&question!.options.length>0&&<div className={`study-options ${question!.compact?"compact":""}`}>{question!.options.map((option,index)=>{const correct=isAnswerOption(option,index,card.detail?.answer||"");const state=revealed?(correct?"correct":selectedOption===index?"wrong":""):"";return <button disabled={mode==="quick"||revealed} className={state} onClick={()=>chooseOption(index)} key={index}><MathText>{option}</MathText>{state==="correct"&&<b>正确</b>}{state==="wrong"&&<b>错误</b>}</button>})}</div>}{isRecallQuestion&&!revealed&&<RecallAnswer card={card} model={model} onScored={result=>{setRecallScore(result);setRating(result.rating);setRevealed(true)}}/>}</div>{recallScore&&<RecallFeedback result={recallScore}/>} {revealed&&<div className="flash-back"><small>{card.type==="背诵"?"原图与参考答案":"答案与解题模型"}</small>{card.type==="背诵"?<>{card.sourceUrl&&<StoredImage src={card.sourceUrl} alt="背诵卡片原图答案"/>}<div className="recall-reference"><StructuredText>{recallScore?.referenceAnswer||card.detail?.answer||card.back}</StructuredText></div></>:<StructuredText>{card.back}</StructuredText>}</div>}<div className="flash-tags">{card.tags.map(t=><span key={t}>#{t}</span>)}</div></div>{mode==="quick"&&!revealed&&<div className="thought-ratings"><button onClick={()=>chooseThought("good")}><b>思路通畅</b><span>知道完整解题路径</span></button><button onClick={()=>chooseThought("hard")}><b>思路阻塞</b><span>有方向但无法推进</span></button><button onClick={()=>chooseThought("again")}><b>毫无思路</b><span>需要重新学习</span></button></div>}{mode==="question"&&!isRecallQuestion&&!revealed&&<p className="study-hint">请选择一个答案，提交后会立即显示结果与解析。</p>}{revealed&&rating&&<button className="study-next" onClick={()=>rate(rating)}>记录结果并进入下一题 →</button>}{notice&&<div className="toast">{notice}</div>}</div></div>
}

function RecallAnswer({card,model,onScored}:{card:Card;model?:ModelChoice;onScored:(result:RecallScore)=>void}){
  const [method,setMethod]=useState<"text"|"voice"|null>(null);const [answer,setAnswer]=useState("");const [recording,setRecording]=useState(false);const [audioUrl,setAudioUrl]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const recorderRef=useRef<MediaRecorder|null>(null);const recognitionRef=useRef<any>(null);const streamRef=useRef<MediaStream|null>(null);const chunksRef=useRef<Blob[]>([]);
  useEffect(()=>()=>{recognitionRef.current?.stop?.();recorderRef.current?.stop?.();streamRef.current?.getTracks().forEach(track=>track.stop());if(audioUrl)URL.revokeObjectURL(audioUrl)},[audioUrl]);
  async function startVoice(){setError("");const Recognition=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Recognition||!navigator.mediaDevices?.getUserMedia){setError("当前浏览器不支持语音识别，请使用文字答题");return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});streamRef.current=stream;chunksRef.current=[];const recorder=new MediaRecorder(stream);recorderRef.current=recorder;recorder.ondataavailable=event=>{if(event.data.size)chunksRef.current.push(event.data)};recorder.onstop=()=>{const blob=new Blob(chunksRef.current,{type:recorder.mimeType||"audio/webm"});if(audioUrl)URL.revokeObjectURL(audioUrl);setAudioUrl(URL.createObjectURL(blob));stream.getTracks().forEach(track=>track.stop())};const recognition=new Recognition();recognition.lang="zh-CN";recognition.continuous=true;recognition.interimResults=true;recognition.onresult=(event:any)=>{let text="";for(let i=0;i<event.results.length;i++)text+=event.results[i][0].transcript;setAnswer(text.trim())};recognition.onerror=(event:any)=>setError(event.error==="no-speech"?"没有识别到语音，请重新录制":"语音识别失败，请重试或改用文字答题");recognitionRef.current=recognition;recorder.start();recognition.start();setRecording(true)}catch{setError("无法打开麦克风，请检查浏览器权限")}}
  function stopVoice(){recognitionRef.current?.stop?.();if(recorderRef.current?.state==="recording")recorderRef.current.stop();setRecording(false)}
  async function submit(){if(!answer.trim()||!model)return;setBusy(true);setError("");try{const response=await fetch("/api/ai/score-recall",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({cardId:card.id,responseText:answer,modelConfigId:model.id,model:model.model})});const data=await response.json();if(!response.ok)throw new Error(data.error||"评分失败");onScored(data)}catch(reason){setError(reason instanceof Error?reason.message:"评分失败")}finally{setBusy(false)}}
  return <section className="recall-answer"><div className="recall-methods"><button className={method==="voice"?"active":""} onClick={()=>setMethod("voice")}>◉<b>语音答题</b><span>录音并自动转写</span></button><button className={method==="text"?"active":""} onClick={()=>setMethod("text")}>Aa<b>文字答题</b><span>输入你的完整回答</span></button></div>{method==="text"&&<textarea value={answer} onChange={event=>setAnswer(event.target.value)} placeholder="输入你回忆的内容…"/>}{method==="voice"&&<div className="voice-answer"><button className={recording?"recording":""} onClick={recording?stopVoice:startVoice}>{recording?"■ 结束录音":"● 开始录音"}</button>{recording&&<span>正在录音并识别…</span>}{audioUrl&&!recording&&<audio controls src={audioUrl}/>}<textarea value={answer} onChange={event=>setAnswer(event.target.value)} placeholder="语音转写结果会显示在这里，也可以手动修正…"/></div>}{error&&<p className="recall-error">{error}</p>}{method&&<button className="recall-submit" disabled={busy||!answer.trim()||!model} onClick={()=>void submit()}>{busy?"AI 正在评分…":model?"提交并评分":"请先配置可用模型"}</button>}</section>
}
function RecallFeedback({result}:{result:RecallScore}){return <section className="recall-feedback"><div className="recall-score"><strong>{result.score}</strong><span>综合得分</span><p>{result.summary}</p></div><div className="recall-feedback-grid"><div className="correct"><b>回答正确</b>{result.correctPoints.length?result.correctPoints.map(item=><span key={item}>✓ {item}</span>):<span>暂无明确命中点</span>}</div><div className="missing"><b>遗漏内容</b>{result.missingPoints.length?result.missingPoints.map(item=><span key={item}>△ {item}</span>):<span>没有明显遗漏</span>}</div>{result.incorrectPoints.length>0&&<div className="incorrect"><b>需要纠正</b>{result.incorrectPoints.map(item=><span key={item}>× {item}</span>)}</div>}</div><p className="recall-suggestion">建议：{result.suggestion}</p></section>}

function localDateKey(date:Date){const year=date.getFullYear();const month=String(date.getMonth()+1).padStart(2,"0");const day=String(date.getDate()).padStart(2,"0");return `${year}-${month}-${day}`}
function DiaryInline({children}:{children:string}){const parts=children.split(/(\*\*.+?\*\*)/g);return <>{parts.map((part,index)=>part.startsWith("**")&&part.endsWith("**")?<strong key={index}>{part.slice(2,-2)}</strong>:<span key={index}>{part}</span>)}</>}
function DiaryContent({entry,onToggle}:{entry:DiaryEntry;onToggle:(entry:DiaryEntry,lineIndex:number,done:boolean)=>void}){return <div className="diary-rich-content">{entry.content.split("\n").map((line,index)=>{const task=line.match(/^\s*-\s*\[([ xX])\]\s*(.*)$/);if(task)return <label className="diary-check-line" key={index}><input type="checkbox" checked={task[1].toLowerCase()==="x"} onChange={event=>onToggle(entry,index,event.target.checked)}/><span><DiaryInline>{task[2]}</DiaryInline></span></label>;const ordered=line.match(/^\s*(\d+)[.、]\s*(.*)$/);if(ordered)return <div className="diary-ordered-line" key={index}><b>{ordered[1]}.</b><span><DiaryInline>{ordered[2]}</DiaryInline></span></div>;return line?<p key={index}><DiaryInline>{line}</DiaryInline></p>:<br key={index}/>})}</div>}
function DiaryPreview({entry}:{entry:DiaryEntry}){const text=entry.content.replace(/\*\*(.*?)\*\*/g,"$1").replace(/^\s*-\s*\[[ xX]\]\s*/gm,"• ").replace(/^\s*\d+[.、]\s*/gm,"").replace(/\n+/g," ").trim();return <><h3>{entry.title}</h3><p>{text}</p></>}
function Diary(){
  const [entries,setEntries]=useState<DiaryEntry[]>(()=>diarySessionCache||[]);
  const [displayMode,setDisplayMode]=useState<"calendar"|"timeline">("calendar");
  const [month,setMonth]=useState(()=>{const now=new Date();return new Date(now.getFullYear(),now.getMonth(),1)});
  const [selectedDate,setSelectedDate]=useState(()=>localDateKey(new Date()));
  const [adding,setAdding]=useState(false);const [editingEntry,setEditingEntry]=useState<DiaryEntry|null>(null);const [viewingEntry,setViewingEntry]=useState<DiaryEntry|null>(null);
  const [title,setTitle]=useState("");const [content,setContent]=useState("");const [entryDate,setEntryDate]=useState(()=>localDateKey(new Date()));
  const diaryTextarea=useRef<HTMLTextAreaElement>(null);
  const [loading,setLoading]=useState(!diarySessionCache);const [cacheReady,setCacheReady]=useState(!!diarySessionCache);const [refreshing,setRefreshing]=useState(false);const [saving,setSaving]=useState(false);const [deletingId,setDeletingId]=useState<string|null>(null);const [error,setError]=useState("");
  useEffect(()=>{let cancelled=false;if(!diarySessionCache){try{const cached=JSON.parse(window.localStorage.getItem("learner-diary-cache")||"null");if(Array.isArray(cached)){setEntries(cached);setLoading(false)}}catch{}setCacheReady(true)}else setCacheReady(true);setRefreshing(true);fetch("/api/diaries").then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||"读取日记失败");if(!cancelled)setEntries(data.entries||[])}).catch(reason=>{if(!cancelled)setError(reason instanceof Error?reason.message:"读取日记失败")}).finally(()=>{if(!cancelled){setLoading(false);setRefreshing(false)}});return()=>{cancelled=true}},[]);
  useEffect(()=>{if(!cacheReady)return;diarySessionCache=entries;try{window.localStorage.setItem("learner-diary-cache",JSON.stringify(entries))}catch{}},[entries,cacheReady]);
  const entriesByDate=useMemo(()=>entries.reduce<Record<string,DiaryEntry[]>>((result,entry)=>{(result[entry.entryDate]??=[]).push(entry);return result},{}),[entries]);
  const calendarDays=useMemo(()=>{const first=new Date(month.getFullYear(),month.getMonth(),1);const offset=(first.getDay()+6)%7;const start=new Date(first);start.setDate(1-offset);return Array.from({length:42},(_,index)=>{const date=new Date(start);date.setDate(start.getDate()+index);return date})},[month]);
  const selectedEntries=entriesByDate[selectedDate]||[];
  function openAdd(date=selectedDate){setEditingEntry(null);setEntryDate(date);setTitle("");setContent("");setError("");setAdding(true)}
  function openEdit(entry:DiaryEntry){setEditingEntry(entry);setEntryDate(entry.entryDate);setTitle(entry.title);setContent(entry.content);setError("");setAdding(true)}
  function closeEditor(){setAdding(false);setEditingEntry(null);setError("")}
  function formatDiary(kind:"bold"|"ordered"|"check"){const textarea=diaryTextarea.current;if(!textarea)return;const start=textarea.selectionStart;const end=textarea.selectionEnd;const selected=content.slice(start,end);let replacement="";if(kind==="bold")replacement=`**${selected||"重点内容"}**`;else{const lines=(selected||"列表项").split("\n");replacement=lines.map((line,index)=>kind==="ordered"?`${index+1}. ${line.replace(/^\s*\d+[.、]\s*/,"")}`:`- [ ] ${line.replace(/^\s*-\s*\[[ xX]\]\s*/,"")}`).join("\n")}setContent(current=>current.slice(0,start)+replacement+current.slice(end));requestAnimationFrame(()=>{textarea.focus();textarea.setSelectionRange(start,start+replacement.length)})}
  async function toggleDiaryTask(entry:DiaryEntry,lineIndex:number,done:boolean){const lines=entry.content.split("\n");lines[lineIndex]=lines[lineIndex].replace(/^\s*-\s*\[[ xX]\]/,`- [${done?"x":" "}]`);const nextContent=lines.join("\n");setEntries(current=>current.map(item=>item.id===entry.id?{...item,content:nextContent}:item));try{const response=await fetch("/api/diaries",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:entry.id,title:entry.title,content:nextContent,entryDate:entry.entryDate})});const data=await response.json();if(!response.ok)throw new Error(data.error||"更新任务失败");setEntries(current=>current.map(item=>item.id===entry.id?data.entry:item))}catch(reason){setEntries(current=>current.map(item=>item.id===entry.id?entry:item));setError(reason instanceof Error?reason.message:"更新任务失败")}}
  async function removeDiary(entry:DiaryEntry){if(!window.confirm(`确定删除《${entry.title}》吗？删除后无法恢复。`))return;setDeletingId(entry.id);setError("");try{const response=await fetch(`/api/diaries?id=${encodeURIComponent(entry.id)}`,{method:"DELETE"});const data=await response.json();if(!response.ok)throw new Error(data.error||"删除日记失败");setEntries(current=>current.filter(item=>item.id!==entry.id));if(viewingEntry?.id===entry.id)setViewingEntry(null)}catch(reason){setError(reason instanceof Error?reason.message:"删除日记失败")}finally{setDeletingId(null)}}
  async function save(){if(!title.trim()||!content.trim())return;setSaving(true);setError("");try{const response=await fetch("/api/diaries",{method:editingEntry?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:editingEntry?.id,title,content,entryDate})});const data=await response.json();if(!response.ok)throw new Error(data.error||(editingEntry?"更新日记失败":"保存日记失败"));setEntries(current=>(editingEntry?current.map(entry=>entry.id===data.entry.id?data.entry:entry):[data.entry,...current]).sort((a,b)=>b.entryDate.localeCompare(a.entryDate)||b.createdAt.localeCompare(a.createdAt)));setSelectedDate(entryDate);setMonth(new Date(`${entryDate}T12:00:00`));closeEditor()}catch(reason){setError(reason instanceof Error?reason.message:"保存日记失败")}finally{setSaving(false)}}
  if(adding)return <div className="page diary-editor-page"><button className="diary-editor-back" onClick={closeEditor}>← 返回悟道日记</button><div className="diary-editor-heading"><span className="eyebrow">{editingEntry?"修改记录":"新的记录"}</span><h1>{editingEntry?"编辑悟道日记":"写悟道日记"}</h1><p>把今天的学习过程、思考和收获留下来。</p></div><section className="diary-editor-sheet"><div className="diary-editor-meta"><label>日期<input type="date" value={entryDate} onChange={event=>setEntryDate(event.target.value)}/></label><label>标题<input maxLength={80} value={title} onChange={event=>setTitle(event.target.value)} placeholder="今天理解了什么？"/></label></div><label className="diary-body-field"><span>学习记录</span><div className="diary-editor-toolbar"><button type="button" onClick={()=>formatDiary("ordered")}><b>1.</b> 有序列表</button><button type="button" onClick={()=>formatDiary("check")}>☑ 复选任务</button><button type="button" onClick={()=>formatDiary("bold")}><b>B</b> 加粗</button></div><textarea ref={diaryTextarea} maxLength={10000} value={content} onChange={event=>setContent(event.target.value)} placeholder="记录今天的学习过程、思考、难点和收获…"/><small className="diary-format-hint">选中文字后点击格式按钮，或直接使用 **加粗**、1. 列表、- [ ] 任务</small></label>{error&&<div className="upload-message error">! {error}</div>}<footer><button onClick={closeEditor}>取消</button><button className="primary" disabled={saving||!title.trim()||!content.trim()} onClick={()=>void save()}>{saving?"正在保存…":editingEntry?"保存修改":"保存并点亮日历"}</button></footer></section></div>;
  if(viewingEntry){const current=entries.find(entry=>entry.id===viewingEntry.id)||viewingEntry;return <div className="page diary-detail-page"><header><button className="diary-detail-back" onClick={()=>setViewingEntry(null)}>← 返回悟道日记</button><div className="diary-detail-actions"><button aria-label="编辑日记" title="编辑日记" onClick={()=>openEdit(current)}>✎</button><button className="danger" aria-label="删除日记" title="删除日记" disabled={deletingId===current.id} onClick={()=>void removeDiary(current)}>⌫</button></div></header><section className="diary-detail-sheet"><span>{current.entryDate}</span><h1>{current.title}</h1><DiaryContent entry={current} onToggle={(item,line,done)=>void toggleDiaryTask(item,line,done)}/></section>{error&&<div className="upload-message error">! {error}</div>}</div>}
  return <div className="page diary-page">
    <div className="page-heading"><div><span className="eyebrow">学习轨迹</span><h1>悟道日记</h1><p>记录每一次理解、顿悟与成长。</p></div><button className="primary" onClick={()=>openAdd()}>＋ 写日记</button></div>
    <div className="diary-toolbar"><div className="diary-view-switch"><button className={displayMode==="calendar"?"active":""} onClick={()=>setDisplayMode("calendar")}>日历视图</button><button className={displayMode==="timeline"?"active":""} onClick={()=>setDisplayMode("timeline")}>时间轴</button></div><span>已记录 <b>{entries.length}</b> 篇学习日记 {refreshing&&<small className="diary-refreshing">同步中…</small>}</span></div>
    {error&&!adding&&<div className="upload-message error">! {error}</div>}
    {loading?<div className="diary-loading">正在加载学习轨迹…</div>:displayMode==="calendar"?<div className="diary-calendar-layout">
      <section className="diary-calendar"><header><button onClick={()=>setMonth(current=>new Date(current.getFullYear(),current.getMonth()-1,1))}>‹</button><h2>{month.getFullYear()} 年 {month.getMonth()+1} 月</h2><button onClick={()=>setMonth(current=>new Date(current.getFullYear(),current.getMonth()+1,1))}>›</button></header><div className="calendar-weekdays">{["一","二","三","四","五","六","日"].map(day=><span key={day}>{day}</span>)}</div><div className="calendar-grid">{calendarDays.map(date=>{const key=localDateKey(date);const dayEntries=entriesByDate[key]||[];const outside=date.getMonth()!==month.getMonth();return <button key={key} className={`${outside?"outside ":""}${dayEntries.length?"lit ":""}${selectedDate===key?"selected":""}`} onClick={()=>setSelectedDate(key)} onDoubleClick={()=>openAdd(key)}><time>{date.getDate()}</time>{dayEntries.length>0&&<><i></i><small>{dayEntries.length}</small></>}</button>})}</div></section>
      <aside className="diary-day-panel"><small>{selectedDate}</small><h2>{selectedEntries.length?`这一天写了 ${selectedEntries.length} 篇`:"这一天还没有记录"}</h2>{selectedEntries.map(entry=><article className="diary-preview-card" key={entry.id} role="button" tabIndex={0} onClick={()=>setViewingEntry(entry)} onKeyDown={event=>{if(event.key==="Enter"||event.key===" ")setViewingEntry(entry)}}><DiaryPreview entry={entry}/></article>)}<button onClick={()=>openAdd(selectedDate)}>＋ 记录这一天</button></aside>
    </div>:<section className="diary-timeline">{entries.length?entries.map(entry=>{const date=new Date(`${entry.entryDate}T12:00:00`);return <article key={entry.id}><div className="diary-date-card"><strong>{date.getDate()}</strong><span>{date.getFullYear()}.{String(date.getMonth()+1).padStart(2,"0")}</span><small>{["周日","周一","周二","周三","周四","周五","周六"][date.getDay()]}</small></div><div className="diary-entry-card diary-preview-card" role="button" tabIndex={0} onClick={()=>setViewingEntry(entry)} onKeyDown={event=>{if(event.key==="Enter"||event.key===" ")setViewingEntry(entry)}}><DiaryPreview entry={entry}/></div></article>}):<div className="diary-empty"><strong>还没有日记</strong><p>写下第一次学习与思考，点亮你的日历。</p><button className="primary" onClick={()=>openAdd()}>写第一篇日记</button></div>}</section>}
  </div>
}

function Stats({stats}:{stats:StatsData}){const max=Math.max(1,...stats.trend.map(item=>item.count));return <div className="page"><div className="page-heading"><div><span className="eyebrow">记忆趋势</span><h1>学习统计</h1><p>全部数据来自你的真实学习记录。</p></div></div><div className="stat-grid"><article><small>近 30 天复习</small><strong>{stats.recent30}</strong><em>今日 {stats.completedToday} 次</em></article><article><small>平均记忆率</small><strong>{stats.retention}%</strong><em>{stats.recent30?"按非 Again 复习计算":"暂无复习记录"}</em></article><article><small>已掌握</small><strong>{stats.mastered}</strong><em>{stats.masteredRate}% 卡片</em></article></div><section className="chart"><h3>近 14 天学习量</h3><div className="bars">{stats.trend.map(item=><i key={item.date} style={{height:`${Math.max(5,item.count/max*100)}%`}} title={`${item.label} · ${item.count} 次`}><span>{item.count}</span></i>)}</div><div className="chart-labels"><span>{stats.trend[0]?.label||"—"}</span><span>{stats.trend[6]?.label||"—"}</span><span>今天</span></div></section></div> }

const providers = {
  openai:{label:"OpenAI",baseUrl:"https://api.openai.com/v1",models:["gpt-5.4","gpt-5.4-mini","gpt-4.1"]},
  anthropic:{label:"Anthropic",baseUrl:"https://api.anthropic.com/v1",models:["claude-sonnet-4-5","claude-opus-4-1"]},
  gemini:{label:"Google Gemini",baseUrl:"https://generativelanguage.googleapis.com/v1beta",models:["gemini-3.1-pro-preview","gemini-2.5-flash"]},
  deepseek:{label:"DeepSeek",baseUrl:"https://api.deepseek.com/v1",models:["deepseek-chat","deepseek-reasoner"]},
  alibaba:{label:"阿里云百炼",baseUrl:"https://dashscope.aliyuncs.com/compatible-mode/v1",models:["qwen-vl-max","qwen-plus"]},
  byteplus:{label:"字节跳动·火山方舟",baseUrl:"https://ark.cn-beijing.volces.com/api/v3",models:["doubao-seed-2-0-pro-260215","doubao-seed-2-0-lite-260215"]},
  custom:{label:"自定义兼容接口",baseUrl:"",models:[] as string[]},
};

function Settings({configs,setConfigs}:{configs:ModelConfig[];setConfigs:Dispatch<SetStateAction<ModelConfig[]>>}){
  const [adding,setAdding]=useState(false);const [provider,setProvider]=useState<keyof typeof providers>("openai");const [model,setModel]=useState(providers.openai.models[0]);const [customModel,setCustomModel]=useState("");const [key,setKey]=useState("");const [baseUrl,setBaseUrl]=useState(providers.openai.baseUrl);const [showKey,setShowKey]=useState(false);const [saving,setSaving]=useState(false);const [settingsError,setSettingsError]=useState("");const [discoveredModels,setDiscoveredModels]=useState<Partial<Record<keyof typeof providers,GoogleModel[]>>>({});const [discovering,setDiscovering]=useState(false);
  function chooseProvider(value:keyof typeof providers){setProvider(value);setModel(providers[value].models[0]||"");setBaseUrl(providers[value].baseUrl);setCustomModel("")}
  async function validate(id:string){setSettingsError("");setConfigs(current=>current.map(config=>config.id===id?{...config,validationStatus:"pending",validationError:null}:config));try{const response=await fetch("/api/models",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,validate:true})});const data=await response.json();if(!response.ok)throw new Error(data.error||"校验失败");setConfigs(current=>current.map(config=>config.id===id?{...config,validationStatus:data.validationStatus,validationError:data.validationError,lastValidatedAt:data.lastValidatedAt}:config))}catch(error){setConfigs(current=>current.map(config=>config.id===id?{...config,validationStatus:"invalid",validationError:error instanceof Error?error.message:"校验失败"}:config))}}
  async function add(){const finalModel=provider==="custom"?customModel:model;if(!key.trim()||!finalModel.trim())return;setSaving(true);setSettingsError("");try{const response=await fetch("/api/models",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({provider,providerLabel:providers[provider].label,model:finalModel,apiKey:key.trim(),baseUrl:baseUrl.trim()})});const data=await response.json();if(!response.ok)throw new Error(data.error||"保存失败");setConfigs(current=>[...current,data.config]);setKey("");setAdding(false)}catch(error){setSettingsError(error instanceof Error?error.message:"保存失败")}finally{setSaving(false)}}
  useEffect(()=>{configs.filter(config=>config.validationStatus==="pending").forEach(config=>void validate(config.id))},[configs.map(config=>`${config.id}:${config.validationStatus}`).join("|")]);
  async function update(id:string,change:Partial<ModelConfig>){setSettingsError("");try{const response=await fetch("/api/models",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,...change})});const data=await response.json();if(!response.ok)throw new Error(data.error||"更新失败");setConfigs(configs.map(c=>c.id===id?{...c,...change,validationStatus:"valid",validationError:null,lastValidatedAt:data.lastValidatedAt}:change.isDefault?{...c,isDefault:false}:c))}catch(error){setSettingsError(error instanceof Error?error.message:"更新失败")}}
  async function remove(id:string){setSettingsError("");try{const response=await fetch(`/api/models?id=${encodeURIComponent(id)}`,{method:"DELETE"});const data=await response.json();if(!response.ok)throw new Error(data.error||"删除失败");setConfigs(configs.filter(c=>c.id!==id))}catch(error){setSettingsError(error instanceof Error?error.message:"删除失败")}}
  async function discoverModels(configId?:string,providerOverride?:keyof typeof providers){const targetProvider=providerOverride||provider;setDiscovering(true);setSettingsError("");try{const response=await fetch("/api/models/discover",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(configId?{configId}:{provider:targetProvider,apiKey:key,baseUrl}),signal:AbortSignal.timeout(15000)});const data=await response.json();if(!response.ok)throw new Error(data.error||"拉取模型失败");const available:GoogleModel[]=data.models||[];setDiscoveredModels(current=>({...current,[targetProvider]:available}));if(!configId&&available.length&&!available.some(item=>item.id===model))setModel(available[0].id)}catch(error){setSettingsError(error instanceof Error&&(error.name==="TimeoutError"||error.name==="AbortError")?"自动拉取模型超时，仍可选择内置模型或稍后重试":error instanceof Error?error.message:"拉取模型失败")}finally{setDiscovering(false)}}
  useEffect(()=>{for(const targetProvider of Object.keys(providers).filter(item=>item!=="custom") as Array<keyof typeof providers>){if(targetProvider in discoveredModels)continue;const saved=configs.find(config=>config.provider===targetProvider&&config.enabled&&config.validationStatus==="valid");if(saved){void discoverModels(saved.id,targetProvider);break}}},[configs,discoveredModels]);
  useEffect(()=>{if(!adding||provider==="custom"||key.trim().length<8)return;const timer=window.setTimeout(()=>void discoverModels(),700);return()=>window.clearTimeout(timer)},[adding,provider,key,baseUrl]);
  const remoteModels=discoveredModels[provider]||[];const selectableModels=remoteModels.length?remoteModels.map(item=>item.id):providers[provider].models;
  return <div className="page settings-page">
    <div className="page-heading"><div><span className="eyebrow">系统设置</span><h1>模型管理</h1><p>管理 AI 解析使用的厂商、模型和 API Key。</p></div><button className="primary" onClick={()=>setAdding(true)}>+ 添加模型</button></div>
    <div className="security-note"><span>✦</span><div><strong>密钥安全</strong><p>API Key 经服务端加密后安全保存，刷新页面或发布新版本都不会丢失。</p></div></div>
    {settingsError&&<div className="upload-message error">! {settingsError}</div>}
    {configs.length===0?<div className="empty-models"><div>⌘</div><h2>还没有可用的 AI 模型</h2><p>添加一个厂商和 API Key，才能开始图片识题与解析。</p><button onClick={()=>setAdding(true)}>+ 添加第一个模型</button></div>:<div className="model-list">{configs.map(config=><article key={config.id}>
      <div className={`provider-logo ${config.provider}`}>{config.providerLabel.slice(0,2)}</div>
      <div className="model-main"><div><h3>{config.providerLabel}</h3>{config.isDefault&&<span>默认解析模型</span>}<span className={`validation-badge ${config.validationStatus}`}>{config.validationStatus==="valid"?"✓ 校验通过":config.validationStatus==="invalid"?"! 校验失败":"校验中"}</span></div>{(config.provider!=="custom"&&discoveredModels[config.provider as keyof typeof providers]?.length)?<select value={config.model} onChange={e=>void update(config.id,{model:e.target.value})}>{discoveredModels[config.provider as keyof typeof providers]!.map(item=><option key={item.id} value={item.id}>{item.name} · {item.id}</option>)}</select>:<strong>{config.model}</strong>}{config.validationStatus==="invalid"&&<div><small className="validation-error">{config.validationError||"模型校验未通过"}</small><button className="retry-validation" onClick={()=>void validate(config.id)}>重新校验</button></div>}</div>
      <label className="switch"><input type="checkbox" checked={config.enabled} onChange={e=>void update(config.id,{enabled:e.target.checked})}/><i></i></label><button className="model-action" disabled={config.isDefault} onClick={()=>void update(config.id,{isDefault:true})}>{config.isDefault?"已默认":"设为默认"}</button><button className="delete-model" onClick={()=>void remove(config.id)}>删除</button>
    </article>)}</div>}
    {adding&&<div className="modal-backdrop" onMouseDown={()=>setAdding(false)}><section className="model-modal" onMouseDown={e=>e.stopPropagation()}><header><div><span className="eyebrow">新建连接</span><h2>添加 AI 模型</h2></div><button onClick={()=>setAdding(false)}>×</button></header>
      <label>模型厂商<select value={provider} onChange={e=>chooseProvider(e.target.value as keyof typeof providers)}>{Object.entries(providers).map(([id,p])=><option key={id} value={id}>{p.label}</option>)}</select></label>
      <label>选择模型 {provider!=="custom"&&<small className="model-sync-status">{discovering?"正在拉取该 Key 可用的模型…":remoteModels.length?`已加载 ${remoteModels.length} 个可用模型`:"输入 API Key 后自动加载"}</small>}{provider==="custom"?<input value={customModel} onChange={e=>setCustomModel(e.target.value)} placeholder="例如 my-vision-model"/>:<select value={model} disabled={discovering} onChange={e=>setModel(e.target.value)}>{selectableModels.map(m=><option key={m}>{m}</option>)}</select>}</label>
      <label>API 地址<input value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} placeholder="https://api.example.com/v1"/></label>
      <label>API Key<div className="key-input"><input type={showKey?"text":"password"} value={key} onChange={e=>setKey(e.target.value)} autoComplete="off" placeholder="在此粘贴 API Key"/><button onClick={()=>setShowKey(v=>!v)}>{showKey?"隐藏":"显示"}</button></div><small>请勿在聊天、文档或截图中分享密钥。</small></label>
      <footer><button onClick={()=>setAdding(false)}>取消</button><button className="primary" disabled={saving||!key.trim()||!(provider==="custom"?customModel:model)} onClick={()=>void add()}>{saving?"正在保存…":"添加模型"}</button></footer>
    </section></div>}
  </div>
}
