"use client";

import { useEffect, useMemo, useState } from "react";
import katex from "katex";
import "katex/dist/katex.min.css";

type View = "home" | "upload" | "cards" | "study" | "stats" | "settings";
type Rating = "again" | "hard" | "good" | "easy";
type ModelConfig = { id:string; provider:string; providerLabel:string; model:string; apiKey?:string; keyLast4?:string; baseUrl:string; enabled:boolean; isDefault:boolean; validationStatus:"pending"|"valid"|"invalid"; validationError?:string|null; lastValidatedAt?:string|null };
type GoogleModel = { id:string; name:string; description:string; inputTokenLimit:number|null; outputTokenLimit:number|null };
type Card = { id:number|string; type:string; front:string; back:string; path:string; tags:string[]; interval:string; tone:string; sourceUrl?:string|null; detail?:{stem:string;options:string[];answer:string;solution:string;thinkingModel:{name:string;description:string;steps:string[]}|null}|null };
type AnalyzedQuestion = { order:number; questionNumber:string; stem:string; options:string[]; answer:string; solution:string; knowledgePoints:{name:string;summary:string}[]; thinkingModel:{name:string;description:string;steps:string[]}; difficulty:number; confirmed?:boolean; tags?:string[] };
type Tag = { id:string; name:string };

function MathText({children,className=""}:{children:string;className?:string}){
  const parts=String(children||"").split(/(\$\$[\s\S]+?\$\$|\\\[[\s\S]+?\\\]|\\\([\s\S]+?\\\)|\$[^$\n]+?\$)/g);
  return <span className={`math-text ${className}`}>{parts.map((part,index)=>{const display=(part.startsWith("$$")&&part.endsWith("$$"))||(part.startsWith("\\[")&&part.endsWith("\\]"));const inline=(part.startsWith("$")&&part.endsWith("$"))||(part.startsWith("\\(")&&part.endsWith("\\)"));if(!display&&!inline)return <span key={index}>{part}</span>;const latex=part.replace(/^\$\$|\$\$$/g,"").replace(/^\$|\$$/g,"").replace(/^\\\[|\\\]$/g,"").replace(/^\\\(|\\\)$/g,"");return <span key={index} className={display?"math-display":"math-inline"} dangerouslySetInnerHTML={{__html:katex.renderToString(latex,{displayMode:display,throwOnError:false,strict:false})}}/>})}</span>
}

function StructuredText({children}:{children:string}){
  const prepared=String(children||"").replace(/\r/g,"").replace(/([^\n])(?=(?:答案|解析|思路|关键|结论|步骤\s*\d*)\s*[:：])/g,"$1\n").replace(/([^\n])(?=\d+[.、]\s*)/g,"$1\n");const lines=prepared.split(/\n+/).map(line=>line.trim()).filter(Boolean);
  return <div className="structured-text">{lines.map((line,index)=>{const heading=line.match(/^(答案|解析|思路|关键|结论|步骤\s*\d*)\s*[:：]\s*(.*)$/);if(heading)return <section className={`structured-section ${heading[1]==="答案"||heading[1]==="结论"?"highlight":""}`} key={index}><strong>{heading[1]}</strong>{heading[2]&&<p><MathText>{heading[2]}</MathText></p>}</section>;const step=line.match(/^(\d+)[.、]\s*(.*)$/);if(step)return <div className="structured-step" key={index}><b>{step[1]}</b><p><MathText>{step[2]}</MathText></p></div>;return <p key={index}><MathText>{line}</MathText></p>})}</div>
}

function questionFront(question:AnalyzedQuestion){const stem=question.stem.trim();const compact=stem.replace(/\s+/g,"");const missing=question.options.filter(option=>!compact.includes(option.replace(/\s+/g,"")));return [stem,...missing].filter(Boolean).join("\n")}
function isAnswerOption(option:string,index:number,answer:string){const letter=String.fromCharCode(65+index);const normalizedAnswer=String(answer||"").trim().toUpperCase();const normalizedOption=String(option||"").trim().toUpperCase();const optionValue=normalizedOption.replace(/^\s*[（(]?\s*[A-Z]\s*[)）.、:]?\s*/,"");if(new RegExp(`(^|[^A-Z])${letter}([^A-Z]|$)`).test(normalizedAnswer))return true;const answerValue=normalizedAnswer.replace(/^(答案|正确答案|选项)\s*[:：]?\s*/,"").replace(/^\s*[（(]?\s*[A-Z]\s*[)）.、:]?\s*/,"").trim();return !!answerValue&&answerValue===optionValue}

const nav = [
  ["home", "首页", "◈"], ["upload", "上传学习内容", "↑"], ["cards", "学习卡片", "▱"], ["stats", "学习统计", "⌑"], ["settings", "设置", "⚙"],
] as const;

export default function Home() {
  const [view, setView] = useState<View>("home");
  const [studyIndex, setStudyIndex] = useState(0);
  const [revealed, setRevealed] = useState(false);
  const [completed, setCompleted] = useState(18);
  const [query, setQuery] = useState("");
  const [uploadMode, setUploadMode] = useState<"memorization" | "question" | null>(null);
  const [notice, setNotice] = useState("");
  const [modelConfigs,setModelConfigs]=useState<ModelConfig[]>([]);
  const [selectedModelId,setSelectedModelId]=useState("");
  const [generatedCards,setGeneratedCards]=useState<Card[]>([]);
  const allCards=generatedCards;
  const dueCards = allCards.slice(0, 2);
  const activeCard = dueCards.length?dueCards[studyIndex % dueCards.length]:undefined;
  const filtered = useMemo(() => allCards.filter(c => `${c.front}${c.tags.join("")}${c.path}`.toLowerCase().includes(query.toLowerCase())), [query,allCards]);
  const availableModels=modelConfigs.filter(c=>c.enabled&&c.validationStatus==="valid");
  const activeModel=availableModels.find(c=>c.id===selectedModelId)||availableModels.find(c=>c.isDefault)||availableModels[0];

  useEffect(()=>{let cancelled=false;fetch("/api/models").then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||"读取模型配置失败");if(!cancelled)setModelConfigs(data.configs||[])}).catch(error=>{if(!cancelled)setNotice(error instanceof Error?error.message:"读取模型配置失败")});return()=>{cancelled=true}},[]);
  useEffect(()=>{let cancelled=false;fetch("/api/cards").then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||"读取卡片失败");if(!cancelled)setGeneratedCards(data.cards||[])}).catch(()=>{});return()=>{cancelled=true}},[]);

  function rate(rating: Rating) {
    const label = { again: "重新学习", hard: "稍后巩固", good: "4 天后复习", easy: "15 天后复习" }[rating];
    setNotice(`已记录·${label}`);
    setCompleted(v => v + 1);
    setTimeout(() => { setStudyIndex(v => v + 1); setRevealed(false); setNotice(""); }, 650);
  }

  return (
    <main className="app-shell">
      <aside className="sidebar">
        <button className="brand" onClick={() => setView("home")}><span className="brand-mark">L</span><span>Learner<small>个人学习机</small></span></button>
        <nav>{nav.map(([id, label, icon]) => <button key={id} className={view === id ? "active" : ""} onClick={() => setView(id as View)}><i>{icon}</i>{label}{id === "cards" && <b>{allCards.length}</b>}</button>)}</nav>
        <div className="sidebar-card"><span>本周连续学习</span><strong>6 <small>天</small></strong><div className="week">{["M","T","W","T","F","S","S"].map((d,i)=><i className={i<6?"done":""} key={i}>{i<6?"✓":d}</i>)}</div></div>
        <button className="profile"><span>林</span><span>林晓宇<small>学习设置</small></span><i>···</i></button>
      </aside>

      <section className="workspace">
        <header className="topbar"><div className="mobile-logo">Learner</div><button className="search" onClick={() => setView("cards")}><span>⌕</span>搜索卡片、标签或目录 <kbd>⌘ K</kbd></button><div className="top-actions"><button>○</button><button>♧</button><span className="avatar">林</span></div></header>

        {view === "home" && <Dashboard onStudy={() => setView("study")} onUpload={() => setView("upload")} onCards={() => setView("cards")} completed={completed} />}
        {view === "cards" && <CardLibrary cards={filtered} query={query} setQuery={setQuery} onStudy={() => setView("study")} onCardDeleted={id=>setGeneratedCards(items=>items.filter(card=>card.id!==id))} />}
        <div className="persistent-upload-workspace" hidden={view!=="upload"}><AIUpload active={view==="upload"} mode={uploadMode} setMode={setUploadMode} model={activeModel} models={availableModels} onModelChange={setSelectedModelId} onCardsGenerated={newCards=>{setGeneratedCards(prev=>[...newCards,...prev]);setView("cards")}} /></div>
        {view === "study" && <Study card={activeCard} revealed={revealed} setRevealed={setRevealed} rate={rate} current={studyIndex+1} notice={notice} onExit={() => setView("home")} />}
        {view === "stats" && <Stats />}
        {view === "settings" && <Settings configs={modelConfigs} setConfigs={setModelConfigs} />}
      </section>
    </main>
  );
}

function Dashboard({onStudy,onUpload,onCards,completed}:{onStudy:()=>void;onUpload:()=>void;onCards:()=>void;completed:number}) {
  return <div className="page dashboard"><div className="eyebrow">周三 · 8月19日</div><h1>早上好，林晓宇 <span>✦</span></h1><p className="lead">今天也来让知识留下来。</p>
    <section className="hero-card"><div className="hero-copy"><div className="hero-label"><i></i>今日学习</div><div className="hero-num">36 <small>张待复习</small></div><p>其中 8 张是易错题，优先复习会更高效</p><button className="primary light" onClick={onStudy}>开始学习 <span>→</span></button></div><div className="orbit"><span className="orb one">逻辑</span><span className="orb two">GCD</span><span className="orb three">if</span><span className="orb four">π</span><div className="rings"></div></div></section>
    <div className="metrics"><article><span className="metric-icon orange">◷</span><div><small>待复习</small><strong>36</strong></div><em>↑ 8 张易错</em></article><article><span className="metric-icon blue">+</span><div><small>今日新卡</small><strong>20</strong></div><em>建议上限 25</em></article><article><span className="metric-icon green">✓</span><div><small>今日已完成</small><strong>{completed}</strong></div><em>{Math.min(100, Math.round(completed/54*100))}% 进度</em></article></div>
    <div className="section-title"><div><h2>继续学习</h2><p>从最近的记忆状态继续</p></div><button onClick={onCards}>查看全部 →</button></div>
    <div className="recent-grid"><article className="recent orange-border"><div><span>数学 · 算术</span><b>12 / 48</b></div><h3>最大公约数与最小公倍数</h3><p>上次学习：昨天</p><progress value="25" max="100" /></article><article className="recent violet-border"><div><span>逻辑 · 形式逻辑</span><b>31 / 65</b></div><h3>充分条件、必要条件与假言命题</h3><p>上次学习：3 天前</p><progress value="48" max="100" /></article></div>
    <section className="create-panel"><div className="spark">✦</div><div><h2>把新知识变成长期记忆</h2><p>上传截图或照片，AI 会拆分知识、解题并生成学习卡片。</p></div><button className="primary" onClick={onUpload}>↑ 上传学习内容</button></section>
  </div>;
}

function CardLibrary({cards:items,query,setQuery,onStudy,onCardDeleted}:{cards:Card[];query:string;setQuery:(v:string)=>void;onStudy:()=>void;onCardDeleted:(id:string|number)=>void}) {
  const [selected,setSelected]=useState<Card|null>(null);const [allTags,setAllTags]=useState<Tag[]>([]);const [tagQuery,setTagQuery]=useState("");const [selectedTags,setSelectedTags]=useState<string[]>([]);
  useEffect(()=>{let cancelled=false;fetch("/api/tags").then(async response=>{const data=await response.json();if(response.ok&&!cancelled)setAllTags(data.tags||[])}).catch(()=>{});return()=>{cancelled=true}},[]);
  const visibleTags=allTags.filter(tag=>tag.name.toLocaleLowerCase().includes(tagQuery.trim().toLocaleLowerCase()));const shown=selectedTags.length?items.filter(card=>selectedTags.every(selectedTag=>card.tags.some(tag=>tag.toLocaleLowerCase()===selectedTag.toLocaleLowerCase()))):items;
  function toggleTag(name:string){setSelectedTags(current=>current.includes(name)?current.filter(tag=>tag!==name):[...current,name])}
  return <div className="page"><div className="page-heading"><div><span className="eyebrow">知识库</span><h1>学习卡片</h1><p>{shown.length} 张生产卡片，每一张都可回溯原始资料。</p></div><button className="primary" disabled={!items.length} onClick={onStudy}>▶ 学习到期卡片</button></div><div className="library-tools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索卡片、标签或目录…"/><button>全部类型 ⌄</button><button>今日待复习</button></div><div className="library-layout"><aside className="tag-sidebar"><header><strong>标签</strong>{selectedTags.length>0&&<button onClick={()=>setSelectedTags([])}>清空</button>}</header><input value={tagQuery} onChange={event=>setTagQuery(event.target.value)} placeholder="搜索标签…"/><nav><button className={selectedTags.length===0?"active":""} onClick={()=>setSelectedTags([])}><span>全部标签</span><b>{items.length}</b></button>{visibleTags.map(tag=><button key={tag.id} className={selectedTags.includes(tag.name)?"active":""} onClick={()=>toggleTag(tag.name)}><span>#{tag.name}</span><b>{items.filter(card=>card.tags.some(name=>name.toLocaleLowerCase()===tag.name.toLocaleLowerCase())).length}</b></button>)}</nav></aside><section className="filtered-cards">{selectedTags.length>0&&<div className="active-tag-filters"><small>已选标签</small>{selectedTags.map(tag=><button key={tag} onClick={()=>toggleTag(tag)}>#{tag} ×</button>)}</div>}<div className="card-list">{shown.map(card=><article className="knowledge-card" key={card.id}><div className={`type-mark ${card.tone}`}>{card.type.slice(0,1)}</div><div className="card-body"><div><span className={`type-pill ${card.tone}`}>{card.type}</span><span className="path">{card.path}</span></div><h3><MathText>{card.front}</MathText></h3><div className="tags">{card.tags.map(tag=><span key={tag}>#{tag}</span>)}</div></div><div className="due"><small>下次复习</small><strong>{card.interval}</strong><button className="detail-trigger" onClick={()=>setSelected(card)}>查看详情</button></div></article>)}</div>{shown.length===0&&<div className="empty-card-results"><strong>{items.length===0?"生产库中还没有学习卡片":"没有符合当前标签的卡片"}</strong><p>{items.length===0?"上传学习内容并生成卡片后，会在这里显示。":"取消部分标签或选择全部标签。"}</p></div>}</section></div>{selected&&<CardDetail card={selected} onClose={()=>setSelected(null)} onDeleted={()=>{onCardDeleted(selected.id);setSelected(null)}}/>}</div>;
}

function CardDetail({card,onClose,onDeleted}:{card:Card;onClose:()=>void;onDeleted:()=>void}){
  const detail=card.detail;const [deleting,setDeleting]=useState(false);const [deleteError,setDeleteError]=useState("");
  async function remove(){if(typeof card.id!=="string"||!window.confirm("确定删除这张卡片吗？如果原图还关联其他卡片，原图会继续保留。"))return;setDeleting(true);setDeleteError("");try{const response=await fetch(`/api/cards?id=${encodeURIComponent(card.id)}`,{method:"DELETE"});const data=await response.json();if(!response.ok)throw new Error(data.error||"删除失败");onDeleted()}catch(error){setDeleteError(error instanceof Error?error.message:"删除失败")}finally{setDeleting(false)}}
  return <div className="modal-backdrop card-detail-backdrop" onMouseDown={onClose}><section className="card-detail" onMouseDown={event=>event.stopPropagation()}><header><div><span className="eyebrow">学习卡片详情</span><h2>{card.type}</h2></div><div className="card-detail-actions">{typeof card.id==="string"&&<button className="delete-card" disabled={deleting} onClick={()=>void remove()}>{deleting?"删除中…":"删除卡片"}</button>}<button onClick={onClose}>×</button></div></header>{deleteError&&<div className="upload-message error">! {deleteError}</div>}<div className="card-detail-grid"><aside><small>上传的原图</small>{card.sourceUrl?<img src={card.sourceUrl} alt="卡片原始上传图片"/>:<div className="missing-source">该历史卡片未保存原图</div>}</aside><main><section><small>题目</small><MathText>{detail?.stem||card.front}</MathText></section>{detail?.options?.length?<div className="detail-options">{detail.options.map((option,index)=><span key={index}><MathText>{option}</MathText></span>)}</div>:null}<section className="answer-panel"><small>{detail?"答案":"答案与解析"}</small><StructuredText>{detail?.answer||card.back}</StructuredText></section>{detail?.solution&&<section className="solution-panel"><small>分步解析</small><StructuredText>{detail.solution}</StructuredText></section>}<section><small>标签</small><div className="tags">{card.tags.map(tag=><span key={tag}>#{tag}</span>)}</div></section>{detail?.thinkingModel&&<section className="detail-thinking"><small>思维模型</small><h3>{detail.thinkingModel.name}</h3><MathText>{detail.thinkingModel.description}</MathText><ol>{detail.thinkingModel.steps.map(step=><li key={step}><MathText>{step}</MathText></li>)}</ol></section>}</main></div></section></div>
}

function Upload({mode,setMode}:{mode:"memorization"|"question"|null;setMode:(m:"memorization"|"question")=>void}) {
  const [file,setFile]=useState<File|null>(null); const [preview,setPreview]=useState(""); const [dragging,setDragging]=useState(false); const [message,setMessage]=useState("");
  function acceptImage(next?:File){if(!next)return;if(!next.type.startsWith("image/")){setMessage("请选择图片文件");return}setFile(next);setMessage("")}
  useEffect(()=>{if(!file){setPreview("");return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);
  useEffect(()=>{function onPaste(event:ClipboardEvent){const image=Array.from(event.clipboardData?.items||[]).find(item=>item.type.startsWith("image/"))?.getAsFile();if(image){event.preventDefault();acceptImage(new File([image],`clipboard-${Date.now()}.${image.type.split("/")[1]||"png"}`,{type:image.type}));setMessage("已从剪贴板粘贴图片")}}window.addEventListener("paste",onPaste);return()=>window.removeEventListener("paste",onPaste)},[]);
  return <div className="page upload-page"><div className="page-heading"><div><span className="eyebrow">AI 学习助手</span><h1>上传学习内容</h1><p>拖拽、点击选择，或直接粘贴截图，让 AI 把它变成可以长期复习的卡片。</p></div></div><div className="upload-layout"><section><div className={`dropzone ${file?"has-file":""} ${dragging?"dragging":""}`} onDragEnter={e=>{e.preventDefault();setDragging(true)}} onDragOver={e=>e.preventDefault()} onDragLeave={e=>{e.preventDefault();setDragging(false)}} onDrop={e=>{e.preventDefault();setDragging(false);acceptImage(e.dataTransfer.files[0])}}><input aria-label="选择图片" type="file" accept="image/*" onChange={e=>acceptImage(e.target.files?.[0])}/>{preview?<><img className="upload-preview" src={preview} alt="待上传图片预览"/><button className="remove-upload" onClick={e=>{e.preventDefault();e.stopPropagation();setFile(null);setMessage("")}} aria-label="移除图片">×</button><div className="file-summary"><strong>{file?.name}</strong><span>{file?`${(file.size/1024/1024).toFixed(2)} MB · ${file.type.replace("image/","").toUpperCase()}`:""}</span></div></>:<><div className="upload-icon">↑</div><h2>{dragging?"松手即可添加图片":"拖拽图片到这里"}</h2><p>点击选择，或按 <kbd>⌘ V</kbd> / <kbd>Ctrl V</kbd> 粘贴截图</p><div className="format-hint">PNG、JPG、WEBP</div></>}</div>{message&&<div className={`upload-message ${file?"success":"error"}`}>{file?"✓":"!"} {message}</div>}<h3 className="mode-title">你希望如何处理这份资料？</h3><div className="mode-grid"><button className={mode==="memorization"?"selected":""} onClick={()=>setMode("memorization")}><i>◇</i><strong>背诵内容</strong><span>提取独立知识点，自动生成问题与答案</span></button><button className={mode==="question"?"selected":""} onClick={()=>setMode("question")}><i>∑</i><strong>题目模式</strong><span>识别并拆题，生成答案、解析与思维模型</span></button></div><button className="primary wide" disabled={!file||!mode}>{file&&mode?"开始 AI 解析 →":"请先上传图片并选择模式"}</button></section><aside className="pipeline"><h3>解析流程</h3>{["图片识别与内容拆分","逐项 AI 理解与生成","你审核、修改 AI 结果","选择并生成学习卡片"].map((x,i)=><div key={x}><b>{i+1}</b><span>{x}<small>{i===2?"结果不会自动入库":""}</small></span></div>)}<p>✦ 原始资料会永久保留，每张卡片都可回溯来源。</p></aside></div></div>
}

function AIUpload({active,mode,setMode,model,models,onModelChange,onCardsGenerated}:{active:boolean;mode:"memorization"|"question"|null;setMode:(m:"memorization"|"question")=>void;model?:ModelConfig;models:ModelConfig[];onModelChange:(id:string)=>void;onCardsGenerated:(cards:Card[])=>void}){
  const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState("");const [dragging,setDragging]=useState(false);const [phase,setPhase]=useState<"upload"|"analyzing"|"review">("upload");const [progress,setProgress]=useState(0);const [questions,setQuestions]=useState<AnalyzedQuestion[]>([]);const [error,setError]=useState("");
  function acceptImage(next?:File){if(!next)return;if(!next.type.startsWith("image/")){setError("请上传图片文件");return}setFile(next);setError("");setQuestions([]);setPhase("upload")}
  useEffect(()=>{if(!file){setPreview("");return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);
  useEffect(()=>{if(!active)return;function paste(e:ClipboardEvent){const image=Array.from(e.clipboardData?.items||[]).find(i=>i.type.startsWith("image/"))?.getAsFile();if(image){e.preventDefault();acceptImage(image)}}window.addEventListener("paste",paste);return()=>window.removeEventListener("paste",paste)},[active]);
  async function analyze(){if(!file||!mode||!model)return;setPhase("analyzing");setError("");setProgress(12);const timer=setInterval(()=>setProgress(v=>Math.min(v+Math.ceil(Math.random()*8),88)),700);try{const dataUrl=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file)});const response=await fetch("/api/ai/analyze",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({image:dataUrl,mode,modelConfigId:model.id,provider:model.provider,model:model.model,baseUrl:model.baseUrl})});const data=await response.json();if(!response.ok)throw new Error(data.error||"AI 解析失败");setQuestions((data.questions||[]).map((q:AnalyzedQuestion)=>({...q,confirmed:false,tags:[...new Set((q.knowledgePoints||[]).map(point=>point.name).filter(Boolean))]})));setProgress(100);setTimeout(()=>setPhase("review"),350)}catch(e){setError(e instanceof Error?e.message:"解析失败");setPhase("upload")}finally{clearInterval(timer)}}
  function updateQuestion(index:number,patch:Partial<AnalyzedQuestion>){setQuestions(items=>items.map((q,i)=>i===index?{...q,...patch}:q))}
  async function generateCards(){setError("");const drafts=questions.filter(q=>q.confirmed).map(q=>({front:questionFront(q),back:`答案：${q.answer}\n\n解析：${q.solution}`,stem:q.stem,options:q.options,answer:q.answer,solution:q.solution,thinkingModel:q.thinkingModel,tags:q.tags||[]}));try{const sourceImage=file?await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file)}):null;const response=await fetch("/api/cards",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({cards:drafts,sourceImage,sourceName:file?.name})});const data=await response.json();if(!response.ok)throw new Error(data.error||"保存卡片失败");onCardsGenerated(data.cards||[])}catch(e){setError(e instanceof Error?e.message:"保存卡片失败")}}
  if(phase==="analyzing")return <div className="page analysis-page"><div className="analysis-loader"><div className="scan-art"><img src={preview} alt="正在解析"/><i style={{top:`${Math.min(progress,92)}%`}}></i></div><span className="eyebrow">AI PIPELINE</span><h1>正在识别并拆分题目…</h1><p>{progress<35?"识别题目边界与公式":progress<65?"逐题生成答案与解析":"提炼知识点和可迁移思维模型"}</p><div className="analysis-progress"><i style={{width:`${progress}%`}}></i></div><b>{progress}%</b><small>请不要关闭页面，复杂题目可能需要几十秒</small></div></div>;
  if(phase==="review")return <div className="page review-page"><div className="review-heading"><div><span className="eyebrow">AI 解析完成</span><h1>识别到 {questions.length} 道题</h1><p>请逐题审核。数学公式已自动排版，需要时可点击编辑。</p></div><button className="secondary" onClick={()=>setPhase("upload")}>重新上传</button></div>{error&&<div className="upload-message error">! {error}</div>}<div className="review-list">{questions.map((q,index)=><QuestionReview key={index} question={q} index={index} onUpdate={patch=>updateQuestion(index,patch)}/>)}</div><div className="review-footer"><span>已确认 {questions.filter(q=>q.confirmed).length} / {questions.length} 道题</span><button className="primary" disabled={!questions.some(q=>q.confirmed)} onClick={()=>void generateCards()}>为已确认题目生成 {questions.filter(q=>q.confirmed).length} 张卡片 →</button></div></div>;
  return <div className="page upload-page"><div className="page-heading"><div><span className="eyebrow">AI 学习助手</span><h1>上传学习内容</h1><p>拖拽、点击选择，或直接粘贴截图。</p></div>{models.length?<label className="active-model model-quick-select"><span>✦ 快速切换模型</span><select aria-label="选择 AI 模型" value={model?.id||""} onChange={e=>onModelChange(e.target.value)}>{models.map(item=><option value={item.id} key={item.id}>{item.providerLabel} · {item.model}</option>)}</select><small>仅显示已验证且启用的模型</small></label>:<div className="active-model model-unavailable"><strong>暂无可用模型</strong><span>请先在设置中添加并验证 API Key</span></div>}</div><div className="upload-layout"><section><div className={`dropzone ${file?"has-file":""} ${dragging?"dragging":""}`} onDragEnter={e=>{e.preventDefault();setDragging(true)}} onDragOver={e=>e.preventDefault()} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);acceptImage(e.dataTransfer.files[0])}}><input aria-label="选择图片" type="file" accept="image/*" onChange={e=>acceptImage(e.target.files?.[0])}/>{preview?<><img className="upload-preview" src={preview} alt="待解析图片"/><button className="remove-upload" onClick={e=>{e.preventDefault();e.stopPropagation();setFile(null)}}>×</button><div className="file-summary"><strong>{file?.name}</strong><span>{file?`${(file.size/1024/1024).toFixed(2)} MB`:""}</span></div></>:<><div className="upload-icon">↑</div><h2>{dragging?"松手即可添加图片":"拖拽图片到这里"}</h2><p>点击选择，或按 <kbd>⌘ V</kbd> / <kbd>Ctrl V</kbd> 粘贴</p></>}</div>{error&&<div className="upload-message error">! {error}</div>}<h3 className="mode-title">你希望如何处理这份资料？</h3><div className="mode-grid"><button className={mode==="memorization"?"selected":""} onClick={()=>setMode("memorization")}><i>◇</i><strong>背诵内容</strong><span>提取知识点并生成问答</span></button><button className={mode==="question"?"selected":""} onClick={()=>setMode("question")}><i>∑</i><strong>题目模式</strong><span>拆题、解答、解析与思维模型</span></button></div><button className="primary wide" disabled={!file||!mode||!model} onClick={analyze}>{!model?"请先在设置中添加并验证模型":file&&mode?"开始 AI 解析 →":"请先上传图片并选择模式"}</button></section><aside className="pipeline"><h3>真实解析流程</h3>{["识别题目数量并拆分","逐题生成答案与解析","总结知识点与思维模型","人工确认后生成多张卡片"].map((x,i)=><div key={x}><b>{i+1}</b><span>{x}</span></div>)}</aside></div></div>
}

function QuestionReview({question:q,index,onUpdate}:{question:AnalyzedQuestion;index:number;onUpdate:(patch:Partial<AnalyzedQuestion>)=>void}){
  const [editing,setEditing]=useState(false);
  return <article className={q.confirmed?"confirmed":""}><header><div><b>题目 {q.questionNumber||index+1}</b><span>难度 {q.difficulty}/5</span></div><div className="review-actions"><button type="button" onClick={()=>setEditing(value=>!value)}>{editing?"完成编辑":"编辑内容"}</button><label><input type="checkbox" checked={!!q.confirmed} onChange={e=>onUpdate({confirmed:e.target.checked})}/>{q.confirmed?"已确认":"确认无误"}</label></div></header>
    {editing?<><label>原始题目<textarea value={q.stem} onChange={e=>onUpdate({stem:e.target.value})}/></label>{q.options.length>0&&<div className="review-options">{q.options.map((option,i)=><input key={i} value={option} onChange={e=>onUpdate({options:q.options.map((item,j)=>j===i?e.target.value:item)})}/>)}</div>}<div className="review-columns"><label>AI 答案<textarea value={q.answer} onChange={e=>onUpdate({answer:e.target.value})}/></label><label>AI 解析<textarea value={q.solution} onChange={e=>onUpdate({solution:e.target.value})}/></label></div></>:<><section className="rendered-field"><small>原始题目</small><MathText>{q.stem}</MathText></section>{q.options.length>0&&<div className="review-options rendered-options">{q.options.map((option,i)=><span className={isAnswerOption(option,i,q.answer)?"correct-option":""} key={i}><MathText>{option}</MathText>{isAnswerOption(option,i,q.answer)&&<b>AI 答案</b>}</span>)}</div>}<section className="rendered-field solution solution-panel full-solution"><small>AI 分步解析</small><StructuredText>{q.solution}</StructuredText></section></>}
    {editing&&<TagPicker selected={q.tags||[]} onChange={tags=>onUpdate({tags})}/>}<div className="knowledge-row"><div><small>卡片标签</small>{(q.tags||[]).map(tag=><span key={tag}>#{tag}</span>)}</div><div className="thinking-box"><small>思维模型</small><strong>{q.thinkingModel.name}</strong><p><MathText>{q.thinkingModel.description}</MathText></p><ol>{q.thinkingModel.steps.map(step=><li key={step}><MathText>{step}</MathText></li>)}</ol></div></div>
  </article>
}

function TagPicker({selected,onChange}:{selected:string[];onChange:(tags:string[])=>void}){
  const [allTags,setAllTags]=useState<Tag[]>([]);const [query,setQuery]=useState("");const [busy,setBusy]=useState(false);const [tagError,setTagError]=useState("");
  async function load(){try{const response=await fetch("/api/tags");const data=await response.json();if(response.ok)setAllTags(data.tags||[])}catch{}}
  useEffect(()=>{void load();const refresh=()=>void load();window.addEventListener("learner-tags-changed",refresh);return()=>window.removeEventListener("learner-tags-changed",refresh)},[]);
  const normalized=query.trim().replace(/\s+/g," ").toLocaleLowerCase();const matches=allTags.filter(tag=>tag.name.toLocaleLowerCase().includes(normalized)&&!selected.some(name=>name.toLocaleLowerCase()===tag.name.toLocaleLowerCase()));const exact=allTags.find(tag=>tag.name.toLocaleLowerCase()===normalized);
  function add(name:string){if(selected.some(tag=>tag.toLocaleLowerCase()===name.toLocaleLowerCase()))return;onChange([...selected,name]);setQuery("")}
  async function create(){if(!normalized||exact)return exact&&add(exact.name);setBusy(true);setTagError("");try{const response=await fetch("/api/tags",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:query})});const data=await response.json();if(!response.ok)throw new Error(data.error||"创建标签失败");add(data.tag.name);window.dispatchEvent(new Event("learner-tags-changed"))}catch(error){setTagError(error instanceof Error?error.message:"创建标签失败")}finally{setBusy(false)}}
  return <section className="tag-editor"><div className="tag-editor-heading"><div><small>卡片标签</small><strong>搜索已有标签，或创建新标签</strong></div><span>已选 {selected.length} 个</span></div><div className="selected-tags">{selected.map(tag=><button key={tag} onClick={()=>onChange(selected.filter(name=>name!==tag))}>#{tag} ×</button>)}</div><div className="tag-search"><input value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"){event.preventDefault();void create()}}} placeholder="输入标签名称…"/>{normalized&&!exact&&<button disabled={busy} onClick={()=>void create()}>{busy?"创建中…":`+ 创建“${query.trim()}”`}</button>}</div>{normalized&&<div className="tag-results">{matches.map(tag=><button key={tag.id} onClick={()=>add(tag.name)}>#{tag.name}</button>)}{exact&&selected.some(name=>name.toLocaleLowerCase()===normalized)&&<small>该标签已添加，不能重复。</small>}</div>}{tagError&&<p className="tag-error">{tagError}</p>}</section>
}

function Study({card,revealed,setRevealed,rate,current,notice,onExit}:{card?:Card;revealed:boolean;setRevealed:(v:boolean)=>void;rate:(r:Rating)=>void;current:number;notice:string;onExit:()=>void}) { if(!card)return <div className="study-page"><header><button onClick={onExit}>×</button><div><span>今日学习</span></div><button>···</button></header><div className="study-stage"><div className="empty-card-results"><strong>暂无可学习的生产卡片</strong><p>请先上传学习内容并生成卡片。</p><button className="primary" onClick={onExit}>返回首页</button></div></div></div>;return <div className="study-page"><header><button onClick={onExit}>×</button><div><span>今日学习</span><progress value={current} max="36"/><b>{current} / 36</b></div><button>···</button></header><div className="study-stage"><div className={`flashcard ${revealed?"revealed":""}`}><div className="flash-meta"><span>{card.type}</span><small>{card.path}</small></div><div className="flash-front"><small>问题</small><h2><MathText>{card.front}</MathText></h2></div>{revealed&&<div className="flash-back"><small>答案与解题模型</small><StructuredText>{card.back}</StructuredText></div>}<div className="flash-tags">{card.tags.map(t=><span key={t}>#{t}</span>)}</div></div>{!revealed?<button className="reveal" onClick={()=>setRevealed(true)}>查看答案 <kbd>Space</kbd></button>:<div className="ratings"><p>这次回忆得怎么样？</p><div><button onClick={()=>rate("again")}><b>Again</b><span>完全忘记</span><kbd>1</kbd></button><button onClick={()=>rate("hard")}><b>Hard</b><span>比较困难</span><kbd>2</kbd></button><button onClick={()=>rate("good")}><b>Good</b><span>正常想起</span><kbd>3</kbd></button><button onClick={()=>rate("easy")}><b>Easy</b><span>非常熟练</span><kbd>4</kbd></button></div></div>}{notice&&<div className="toast">{notice}</div>}</div></div> }

function Stats(){ return <div className="page"><div className="page-heading"><div><span className="eyebrow">记忆趋势</span><h1>学习统计</h1><p>看见每一次回忆如何让知识更牢固。</p></div></div><div className="stat-grid"><article><small>近 30 天复习</small><strong>684</strong><em>↑ 18%</em></article><article><small>平均记忆率</small><strong>87%</strong><em>稳定</em></article><article><small>已掌握</small><strong>426</strong><em>34% 卡片</em></article></div><section className="chart"><h3>近 14 天学习量</h3><div className="bars">{[34,52,41,65,48,72,28,56,82,61,76,90,68,84].map((n,i)=><i key={i} style={{height:`${n}%`}}><span>{n}</span></i>)}</div><div className="chart-labels"><span>8/06</span><span>8/12</span><span>今天</span></div></section></div> }

const providers = {
  openai:{label:"OpenAI",baseUrl:"https://api.openai.com/v1",models:["gpt-5.4","gpt-5.4-mini","gpt-4.1"]},
  anthropic:{label:"Anthropic",baseUrl:"https://api.anthropic.com/v1",models:["claude-sonnet-4-5","claude-opus-4-1"]},
  gemini:{label:"Google Gemini",baseUrl:"https://generativelanguage.googleapis.com/v1beta",models:["gemini-3.1-pro-preview","gemini-2.5-flash"]},
  deepseek:{label:"DeepSeek",baseUrl:"https://api.deepseek.com/v1",models:["deepseek-chat","deepseek-reasoner"]},
  custom:{label:"自定义兼容接口",baseUrl:"",models:[] as string[]},
};

function Settings({configs,setConfigs}:{configs:ModelConfig[];setConfigs:(next:ModelConfig[])=>void}){
  const [adding,setAdding]=useState(false);const [provider,setProvider]=useState<keyof typeof providers>("openai");const [model,setModel]=useState(providers.openai.models[0]);const [customModel,setCustomModel]=useState("");const [key,setKey]=useState("");const [baseUrl,setBaseUrl]=useState(providers.openai.baseUrl);const [showKey,setShowKey]=useState(false);const [saving,setSaving]=useState(false);const [settingsError,setSettingsError]=useState("");const [googleModels,setGoogleModels]=useState<GoogleModel[]>([]);const [discovering,setDiscovering]=useState(false);
  function chooseProvider(value:keyof typeof providers){setProvider(value);setModel(providers[value].models[0]||"");setBaseUrl(providers[value].baseUrl);setCustomModel("")}
  async function add(){const finalModel=provider==="custom"?customModel:model;if(!key.trim()||!finalModel.trim())return;setSaving(true);setSettingsError("");try{const response=await fetch("/api/models",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({provider,providerLabel:providers[provider].label,model:finalModel,apiKey:key.trim(),baseUrl:baseUrl.trim()})});const data=await response.json();if(!response.ok)throw new Error(data.error||"保存失败");setConfigs([...configs,data.config]);setKey("");setAdding(false)}catch(error){setSettingsError(error instanceof Error?error.message:"保存失败")}finally{setSaving(false)}}
  async function update(id:string,change:Partial<ModelConfig>){setSettingsError("");try{const response=await fetch("/api/models",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,...change})});const data=await response.json();if(!response.ok)throw new Error(data.error||"更新失败");setConfigs(configs.map(c=>c.id===id?{...c,...change,validationStatus:"valid",validationError:null,lastValidatedAt:data.lastValidatedAt}:change.isDefault?{...c,isDefault:false}:c))}catch(error){setSettingsError(error instanceof Error?error.message:"更新失败")}}
  async function remove(id:string){setSettingsError("");try{const response=await fetch(`/api/models?id=${encodeURIComponent(id)}`,{method:"DELETE"});const data=await response.json();if(!response.ok)throw new Error(data.error||"删除失败");setConfigs(configs.filter(c=>c.id!==id))}catch(error){setSettingsError(error instanceof Error?error.message:"删除失败")}}
  async function discoverGoogle(configId?:string){setDiscovering(true);setSettingsError("");try{const response=await fetch("/api/models/discover",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(configId?{configId}:{apiKey:key,baseUrl})});const data=await response.json();if(!response.ok)throw new Error(data.error||"拉取模型失败");const available:GoogleModel[]=data.models||[];setGoogleModels(available);if(!configId&&available.length&&!available.some(item=>item.id===model))setModel(available.find(item=>item.id==="gemini-3.1-pro-preview")?.id||available[0].id)}catch(error){setSettingsError(error instanceof Error?error.message:"拉取模型失败")}finally{setDiscovering(false)}}
  useEffect(()=>{if(googleModels.length)return;const saved=configs.find(config=>config.provider==="gemini"&&config.enabled);if(saved)void discoverGoogle(saved.id)},[configs,googleModels.length]);
  useEffect(()=>{if(!adding||provider!=="gemini"||key.trim().length<16)return;const timer=window.setTimeout(()=>void discoverGoogle(),700);return()=>window.clearTimeout(timer)},[adding,provider,key,baseUrl]);
  const selectableModels=provider==="gemini"&&googleModels.length?googleModels.map(item=>item.id):providers[provider].models;
  return <div className="page settings-page">
    <div className="page-heading"><div><span className="eyebrow">系统设置</span><h1>模型管理</h1><p>管理 AI 解析使用的厂商、模型和 API Key。</p></div><button className="primary" onClick={()=>setAdding(true)}>+ 添加模型</button></div>
    <div className="security-note"><span>✦</span><div><strong>密钥安全</strong><p>API Key 经服务端加密后保存在生产数据库，列表中只显示末四位；刷新页面或发布新版本都不会丢失。</p></div></div>
    {settingsError&&<div className="upload-message error">! {settingsError}</div>}
    {configs.length===0?<div className="empty-models"><div>⌘</div><h2>还没有可用的 AI 模型</h2><p>添加一个厂商和 API Key，才能开始图片识题与解析。</p><button onClick={()=>setAdding(true)}>+ 添加第一个模型</button></div>:<div className="model-list">{configs.map(config=><article key={config.id}>
      <div className={`provider-logo ${config.provider}`}>{config.providerLabel.slice(0,2)}</div>
      <div className="model-main"><div><h3>{config.providerLabel}</h3>{config.isDefault&&<span>默认解析模型</span>}<span className={`validation-badge ${config.validationStatus}`}>{config.validationStatus==="valid"?"✓ 已验证":config.validationStatus==="invalid"?"! 验证失败":"验证中"}</span></div>{config.provider==="gemini"&&googleModels.length?<select value={config.model} onChange={e=>void update(config.id,{model:e.target.value})}>{googleModels.map(item=><option key={item.id} value={item.id}>{item.name} · {item.id}</option>)}</select>:<strong>{config.model}</strong>}<small>{config.baseUrl} · Key ••••{config.keyLast4||config.apiKey?.slice(-4)||""}</small>{config.validationStatus==="invalid"&&config.validationError&&<small className="validation-error">{config.validationError}</small>}</div>
      <label className="switch"><input type="checkbox" checked={config.enabled} onChange={e=>void update(config.id,{enabled:e.target.checked})}/><i></i></label><button className="model-action" disabled={config.isDefault} onClick={()=>void update(config.id,{isDefault:true})}>{config.isDefault?"已默认":"设为默认"}</button><button className="delete-model" onClick={()=>void remove(config.id)}>删除</button>
    </article>)}</div>}
    {adding&&<div className="modal-backdrop" onMouseDown={()=>setAdding(false)}><section className="model-modal" onMouseDown={e=>e.stopPropagation()}><header><div><span className="eyebrow">新建连接</span><h2>添加 AI 模型</h2></div><button onClick={()=>setAdding(false)}>×</button></header>
      <label>模型厂商<select value={provider} onChange={e=>chooseProvider(e.target.value as keyof typeof providers)}>{Object.entries(providers).map(([id,p])=><option key={id} value={id}>{p.label}</option>)}</select></label>
      <label>选择模型 {provider==="gemini"&&<small className="model-sync-status">{discovering?"正在自动拉取…":googleModels.length?`已同步 ${googleModels.length} 个可用模型`:"输入 API Key 后自动拉取"}</small>}{provider==="custom"?<input value={customModel} onChange={e=>setCustomModel(e.target.value)} placeholder="例如 my-vision-model"/>:<select value={model} disabled={provider==="gemini"&&discovering} onChange={e=>setModel(e.target.value)}>{selectableModels.map(m=><option key={m}>{m}</option>)}</select>}</label>
      <label>API 地址<input value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} placeholder="https://api.example.com/v1"/></label>
      <label>API Key<div className="key-input"><input type={showKey?"text":"password"} value={key} onChange={e=>setKey(e.target.value)} autoComplete="off" placeholder="在此粘贴 API Key"/><button onClick={()=>setShowKey(v=>!v)}>{showKey?"隐藏":"显示"}</button></div><small>请勿在聊天、文档或截图中分享密钥。</small></label>
      <footer><button onClick={()=>setAdding(false)}>取消</button><button className="primary" disabled={saving||!key.trim()||!(provider==="custom"?customModel:model)} onClick={()=>void add()}>{saving?"正在保存…":"添加模型"}</button></footer>
    </section></div>}
  </div>
}
