import { and, asc, eq, inArray } from "drizzle-orm";
import { getDb } from "../../../db";
import { learningCards, learningCardTags, tags, users } from "../../../db/schema";

function identity(request:Request){return {id:request.headers.get("oai-authenticated-user-id")||"local-user",email:request.headers.get("oai-authenticated-user-email")||"local@learner.app"}}
function normalize(value:string){return value.trim().replace(/\s+/g," ").toLocaleLowerCase()}
async function ensureUser(request:Request){const user=identity(request);await getDb().insert(users).values({id:user.id,email:user.email,name:null,timezone:"Asia/Shanghai",createdAt:new Date(),updatedAt:new Date()}).onConflictDoNothing();return user.id}

export async function GET(request:Request){try{const uid=await ensureUser(request);const db=getDb();const rows=await db.select().from(learningCards).where(eq(learningCards.userId,uid)).orderBy(asc(learningCards.createdAt));if(!rows.length)return Response.json({cards:[]});const links=await db.select({cardId:learningCardTags.learningCardId,name:tags.name}).from(learningCardTags).innerJoin(tags,eq(tags.id,learningCardTags.tagId)).where(inArray(learningCardTags.learningCardId,rows.map(row=>row.id)));return Response.json({cards:rows.map(row=>({id:row.id,type:row.cardType==="question"?"原题":"知识点",front:row.front,back:row.back,path:"AI 解析 / 待归类",tags:links.filter(link=>link.cardId===row.id).map(link=>link.name),interval:"新卡片",tone:"orange"}))})}catch(error){return Response.json({error:error instanceof Error?error.message:"读取卡片失败"},{status:500})}}

export async function POST(request:Request){try{const uid=await ensureUser(request);const body=await request.json();if(!Array.isArray(body.cards)||!body.cards.length)return Response.json({error:"没有可保存的卡片"},{status:400});const db=getDb();const created=[];for(const input of body.cards){const now=new Date();const card={id:crypto.randomUUID(),userId:uid,cardType:"question" as const,front:String(input.front||""),back:String(input.back||""),explanation:null,directoryId:null,status:"active" as const,archivedAt:null,createdAt:now,updatedAt:now};await db.insert(learningCards).values(card);const uniqueNames=[...new Map((Array.isArray(input.tags)?input.tags:[]).map((raw:unknown)=>{const name=String(raw).trim().replace(/\s+/g," ");return [normalize(name),name]}).filter(([key])=>key)).entries()];for(const [normalizedName,name] of uniqueNames){let [tag]=await db.select({id:tags.id,name:tags.name}).from(tags).where(and(eq(tags.userId,uid),eq(tags.normalizedName,normalizedName))).limit(1);if(!tag){const id=crypto.randomUUID();await db.insert(tags).values({id,userId:uid,name,normalizedName,createdAt:now,updatedAt:now}).onConflictDoNothing();[tag]=await db.select({id:tags.id,name:tags.name}).from(tags).where(and(eq(tags.userId,uid),eq(tags.normalizedName,normalizedName))).limit(1)}if(tag)await db.insert(learningCardTags).values({learningCardId:card.id,tagId:tag.id}).onConflictDoNothing()}created.push({id:card.id,type:"原题",front:card.front,back:card.back,path:"AI 解析 / 待归类",tags:uniqueNames.map(([,name])=>name),interval:"新卡片",tone:"orange"})}return Response.json({cards:created},{status:201})}catch(error){return Response.json({error:error instanceof Error?error.message:"保存卡片失败"},{status:500})}}
