import { and, eq } from "drizzle-orm";
import { env } from "cloudflare:workers";
import { getDb } from "../../../../db";
import { learningCards, modelConfigs, sourceAssets } from "../../../../db/schema";
import { decryptApiKey } from "../../../../lib/model-secrets";

const resultSchema={type:"object",additionalProperties:false,required:["score","rating","summary","correctPoints","missingPoints","incorrectPoints","suggestion","referenceAnswer","keyPoints"],properties:{score:{type:"integer",minimum:0,maximum:100},rating:{type:"string",enum:["again","hard","good","easy"]},summary:{type:"string"},correctPoints:{type:"array",items:{type:"string"}},missingPoints:{type:"array",items:{type:"string"}},incorrectPoints:{type:"array",items:{type:"string"}},suggestion:{type:"string"},referenceAnswer:{type:"string"},keyPoints:{type:"array",items:{type:"string"}}}};
function outputText(data:any){if(typeof data.output_text==="string")return data.output_text;for(const item of data.output||[])for(const content of item.content||[])if(content.type==="output_text"&&content.text)return content.text;return ""}
function cleanJson(raw:string){return raw.replace(/^```json\s*/i,"").replace(/```$/i,"").trim()}
function normalizeResult(value:any){const score=Math.max(0,Math.min(100,Math.round(Number(value.score)||0)));const rating=score>=90?"easy":score>=75?"good":score>=50?"hard":"again";return {...value,score,rating,summary:String(value.summary||""),correctPoints:Array.isArray(value.correctPoints)?value.correctPoints.map(String):[],missingPoints:Array.isArray(value.missingPoints)?value.missingPoints.map(String):[],incorrectPoints:Array.isArray(value.incorrectPoints)?value.incorrectPoints.map(String):[],suggestion:String(value.suggestion||""),referenceAnswer:String(value.referenceAnswer||""),keyPoints:Array.isArray(value.keyPoints)?value.keyPoints.map(String):[]}}

export async function POST(request:Request){
  try{
    const uid=request.headers.get("oai-authenticated-user-id")||"local-user";const body=await request.json();const responseText=String(body.responseText||"").trim();if(!responseText)return Response.json({error:"请先完成回答"},{status:400});
    const db=await getDb();const [card]=await db.select().from(learningCards).where(and(eq(learningCards.id,String(body.cardId||"")),eq(learningCards.userId,uid))).limit(1);if(!card||card.cardType!=="memorization")return Response.json({error:"背诵卡片不存在"},{status:404});
    const [config]=await db.select().from(modelConfigs).where(and(eq(modelConfigs.id,String(body.modelConfigId||"")),eq(modelConfigs.userId,uid))).limit(1);if(!config||!config.enabled||config.validationStatus!=="valid")return Response.json({error:"请先配置并验证评分模型"},{status:404});
    const detail=(()=>{try{return card.explanation?JSON.parse(card.explanation):{}}catch{return {}}})();let referenceAnswer=String(detail.referenceAnswer||detail.answer||card.back||"").trim();if(referenceAnswer==="查看原图"||referenceAnswer==="请对照原图完成回忆")referenceAnswer="";let image:string|undefined;
    if(!referenceAnswer&&card.sourceAssetId){const [asset]=await db.select().from(sourceAssets).where(and(eq(sourceAssets.id,card.sourceAssetId),eq(sourceAssets.userId,uid))).limit(1);if(asset){const object=await env.UPLOADS.get(asset.storageKey);if(object){const bytes=new Uint8Array(await object.arrayBuffer());let binary="";for(let index=0;index<bytes.length;index+=0x8000)binary+=String.fromCharCode(...bytes.subarray(index,index+0x8000));image=`data:${asset.mimeType};base64,${btoa(binary)}`}}}
    if(!referenceAnswer&&!image)return Response.json({error:"该旧卡片缺少参考答案和原图，暂时无法进行 AI 评分"},{status:422});
    const prompt=`你是严格但友善的背诵评分老师。比较学习者回答与参考资料，按语义覆盖度评分，不要求逐字一致。\n评分映射固定为：90-100 easy，75-89 good，50-74 hard，0-49 again。\n必须指出正确点、遗漏点、错误点，并给出一句改进建议。\n${referenceAnswer?`标准参考答案：\n${referenceAnswer}`:"请先根据所附原图准确整理 referenceAnswer 和 keyPoints，再评分。"}\n学习者回答：\n${responseText}\n只输出符合指定结构的 JSON。`;
    const key=await decryptApiKey(config.encryptedApiKey);const model=String(body.model||config.model);const baseUrl=(config.baseUrl||"").replace(/\/$/,"");let raw="";
    if(config.provider==="openai"){
      const content:any[]=[{type:"input_text",text:prompt}];if(image)content.push({type:"input_image",image_url:image,detail:"high"});const response=await fetch(`${baseUrl||"https://api.openai.com/v1"}/responses`,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${key}`},body:JSON.stringify({model,input:[{role:"user",content}],text:{format:{type:"json_schema",name:"recall_score",strict:true,schema:resultSchema}}})});const data=await response.json();if(!response.ok)throw new Error(data?.error?.message||`评分请求失败 (${response.status})`);raw=outputText(data);
    }else if(config.provider==="anthropic"){
      const content:any[]=[];if(image){const match=image.match(/^data:(image\/[^;]+);base64,(.+)$/);if(match)content.push({type:"image",source:{type:"base64",media_type:match[1],data:match[2]}})}content.push({type:"text",text:prompt});const response=await fetch(`${baseUrl||"https://api.anthropic.com/v1"}/messages`,{method:"POST",headers:{"content-type":"application/json","x-api-key":key,"anthropic-version":"2023-06-01"},body:JSON.stringify({model,max_tokens:5000,messages:[{role:"user",content}]})});const data=await response.json();if(!response.ok)throw new Error(data?.error?.message||`评分请求失败 (${response.status})`);raw=data.content?.find((item:any)=>item.type==="text")?.text||"";
    }else if(config.provider==="gemini"){
      const parts:any[]=[{text:prompt}];if(image){const match=image.match(/^data:(image\/[^;]+);base64,(.+)$/);if(match)parts.push({inline_data:{mime_type:match[1],data:match[2]}})}const response=await fetch(`${baseUrl||"https://generativelanguage.googleapis.com/v1beta"}/models/${model}:generateContent?key=${encodeURIComponent(key)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({contents:[{parts}],generationConfig:{responseMimeType:"application/json",responseJsonSchema:resultSchema}})});const data=await response.json();if(!response.ok)throw new Error(data?.error?.message||`评分请求失败 (${response.status})`);raw=data.candidates?.[0]?.content?.parts?.[0]?.text||"";
    }else{
      const compatibleBase=baseUrl||(config.provider==="alibaba"?"https://dashscope.aliyuncs.com/compatible-mode/v1":config.provider==="byteplus"?"https://ark.cn-beijing.volces.com/api/v3":"https://api.deepseek.com/v1");const content:any=image?[{type:"text",text:prompt},{type:"image_url",image_url:{url:image}}]:prompt;const response=await fetch(`${compatibleBase}/chat/completions`,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${key}`},body:JSON.stringify({model,messages:[{role:"user",content}],response_format:{type:"json_object"}})});const data=await response.json();if(!response.ok)throw new Error(data?.error?.message||`评分请求失败 (${response.status})`);raw=data.choices?.[0]?.message?.content||"";
    }
    const result=normalizeResult(JSON.parse(cleanJson(raw)));if(!result.referenceAnswer)result.referenceAnswer=referenceAnswer;if(!result.referenceAnswer)throw new Error("模型未能生成有效参考答案");
    if(!referenceAnswer){detail.referenceAnswer=result.referenceAnswer;detail.keyPoints=result.keyPoints;detail.answer=result.referenceAnswer;await db.update(learningCards).set({back:result.referenceAnswer,explanation:JSON.stringify(detail),updatedAt:new Date()}).where(and(eq(learningCards.id,card.id),eq(learningCards.userId,uid)))}
    return Response.json(result);
  }catch(error){return Response.json({error:error instanceof Error?error.message:"背诵评分失败"},{status:500})}
}
